### ISSUE TITLE
opening cubeviz from the command line results in a different version than if you start cubeviz from inside glue

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#105]

**Comment by brechmos-stsci** [comment]
@astrofrog It seems that if you run glue, load an IFU dataset it doesn't switch over to the cubeviz layout.  Is that something that should happen?  Or, is that something that could happen?

**Comment by astrofrog** [comment]
@brechmos-stsci - that's expected, cubeviz is currently opt-in for glue users. The two ways to start cubeviz in glue (apart from the cubeviz command) are:

* Starting glue with ``glue --startup=cubeviz``

* Going to the Canvas menu and doing 'New fixed layout tab'

I don't think we should assume that any glue user who wants to load a manga cube necessarily wants to use cubeviz so I would be against automatically enabling cubeviz as soon as one of the supported cube formats in cubeviz is read in.

**Comment by brechmos-stsci** [comment]
Ok. That makes sense.  @kassin I am going to close this.  If this is a significant issue, then re-open and we can further discuss.

**Comment by kassin** [comment]
@astrofrog Could there be an easier way of starting up cubeviz from inside glue?
