### ISSUE TITLE
Add a new selection mode which is 'New subset'

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#111]
We should add a new selection mode to the toolbar at the top which forces a new subset to be created.

**Comment by brechmos-stsci** [comment]
@astrofrog Could you clarify what you mean here maybe with a specific use case?  (It seems like a lower priority thing, ie, not January, right?)

**Comment by astrofrog** [comment]
This was done in glue a little while back, but I think it's also not relevant since @drdavella's work
