### ISSUE TITLE
Dashboard whitespace

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#116]
This is a sort of generic visualization philosophy issue for me and you can feel free to ignore it.

We are now using a very large fraction of the screen real-estate for labels, menus and menu bars, status bars, and whitespace. That may be what most people like for the default view and it certainly has the advantage that you can see all the menu options and coordinates, etc. But it means that the views of the actual data are rather small. 

I can think of several was that one might like to toggle the view (e.g. with a hotkey) to get rid of distracting info. 

- Toggle from the side-by-side tiled view of the data, err & dq to the stacked view. In the default layout this doesn't really help if the windows stay the same size. So I guess we would need to think about whether the alternate dashboard view has a completely different layout (e.g. horizontal with the spatial view on the left and spectral view on the right). I can't really visualize whether this would be very useful. Maybe someone has already played with this?

- Toggle the current window to fill the canvas. For the spatial view this could be quite handy. For the spectral view, I could imagine wanting it to change the aspect ratio so I can get more sense of the shapes of spectral features than I can get from the squished horizontal view in the default. Of course one can just drag the handle on this window and do that sort of thing, so making this a toggle isn't a particularly high priority.

- Toggle on and off the labeling on the spatial views. I actually think a better default for these windows would be not to label the axes and use the real-estate to display the pixels. Especially now that we have the cursor readback. Add the option to switch the cursor readback between pixels and RA,Dec and most of the time you don't really need the labels. (You do want to be able to have them for making hardcopies though; but for example in ds9 that's really the only time I ever turn on coordinate labeling).

- Toggle on and off the menu bars with a hotkey. Default to having them on; advanced users will eventually figure out how to toggle them off.

**Comment by brechmos-stsci** [comment]
1, 2, 4 are basically completed by @drdavella and are in a PR. 

Point 3 will have to be discussed with @hcferguson to determine importance etc.

**Comment by brechmos-stsci** [comment]
@drdavella I believe this is done, correct?  If so, please close

**Comment by drdavella** [comment]
We haven't implemented toggling the current view to fill the entire canvas yet. I'm not sure how important that is, though.

**Comment by brechmos-stsci** [comment]
Given the other more science aspects I think that will be a future improvement (i.e., after the next two sprints).

**Comment by drdavella** [comment]
All of these suggestions have been implemented, with the exception of toggling the current window to fill the canvas. Closing this issue, and we will track the remaining feature as part of our effort to make the layout more flexible.
