### ISSUE TITLE
Image window aspect ratio

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#118]
The image windows should default to having square pixels (even as they are resized). 

- The most intuitive default is to have square pixels, regardless of whether the WCS says they are not square when projected on the sky.  
- There should be an option to make the plot have the pixels square in arc seconds by applying the WCS.  (ds9 has this option, for example).

**Comment by drdavella** [comment]
This appears to be addressed by #123.

**Comment by hcferguson** [comment]
Just needs user testing I think.
