### ISSUE TITLE
Contour-map and image overlays

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#124]
A fairly common use case is to want to overlay an image or (more commonly) a contour map on top of another data set. This can go both ways: making a contour map of the individual spectral slices and overlaying them on a continuum image (e.g. from NIRCam) or making a contour map of the continuum image and overlaying it on the cube so it stays there as you scrub through the channels. 

It seems okay to me to require the overlay to either have the same shape in the spatial dimension or have a WCS. 

This is related to issue #90, since overlaying a moment map is a special case of this general functionality.

**Comment by kassin** [comment]
This will be especially important when we have radio data (e.g., ALMA or PdBI) to test.

**Comment by brechmos-stsci** [comment]
The contour map and image overlays have been completed.  If there is other specific work let's open up a new ticket.
