### ISSUE TITLE
All regions selected in images should always be displayed

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#134]
If a user selects a region in the flux/err/DQ maps and then selects a second region, the first region should continue to display.  

Both spectra should display in specviz as is currently the case.

This should work for all regions selected, no matter how many.

**Comment by nmearl** [comment]
I'm not sure I understand what you're doing here, can you elaborate on the steps you're performing?

**Comment by kassin** [comment]
1. select a region on the flux image (it is colored red for example)
2. view its collapsed spectrum in SpecViz (it is colored red)
3. select a second region on the flux image (it is colored green for example)
4. both selected regions (red and green) continue to be displayed on the flux image
5. view the red and green collapsed spectra in SpecViz

**Comment by drdavella** [comment]
This seems like something that needs to be supported at the `glue` level, but maybe @astrofrog can weigh in.

**Comment by nmearl** [comment]
As mentioned a few times in the past, this behavior is already existent. It depends on which data set you current have selected in the data list. E.g. if you're selecting the original data set you loaded into Glue, then you will create a new subset; however, if you're currently selecting the subset, it will modified that current subset.

This is not a bug.

**Comment by drdavella** [comment]
@nmearl agreed that this isn't a bug. Just wondering at this point whether it's possible for cubeviz to support a slightly more intuitive interface on top of the existing glue functionality.
