### ISSUE TITLE
Arithmetic Operations: FLUX vs. Flux

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#136]
The drop-down menu for the viewers lists the flux extension in the MaNGA data cube as "Flux"

However, the Arithmetic Operations box requires that I type "FLUX" and gives an error if I type "Flux"

This is inconsistent.  Perhaps allow for more flexibility in the Arithmetic Operations box, or at least drop the case sensitivity?

**Comment by drdavella** [comment]
There's also a discrepancy between the Cubeviz dropdowns and the Glue viewer option dropdowns: one uses the name `DQ` and the other uses `MASK`.

**Comment by brechmos-stsci** [comment]
Susan, I have seen this problem, but which dataset are you seeing this with?  I know where the issue lies, I want to make sure I fix it and so want to use the dataset you are using.

**Comment by brechmos-stsci** [comment]
The changes with the data_factories and possibly another PR appears to have fixed this issue. Given the datasets I tried the 3-viewer dropdowns, the glue component selection dropdown and the components in the arithmetic panel are all consistent. 

So, I am going to close this Issue as being done.  If someone finds a dataset that is not consistent, please re-open this and post the location of the dataset so I can look into it.
