### ISSUE TITLE
be able to delete region selection in images

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#146]
I would like to be able to delete a region selection made in the images.  Ideally this would be done using the backspace key and/or a "Edit->Undo" option in the glue menu bar. @javerbukh @brechmos-stsci

**Comment by drdavella** [comment]
Right now there is an option under the top-level **Edit** menu called `Undo apply subset`. This is a very basic "undo", but it looks like `glue` doesn't currently support multiple subset selections anyway.

We have noticed that the "undo" functionality doesn't currently apply to the `specviz` window, though, so maybe we can add support for this.

**Comment by brechmos-stsci** [comment]
@astrofrog Is having multiple "subsets" something in the works or being planned for Glue?  Or might there be a bug in Glue/Cubeviz such that multiple regions are not being displayed?

This seems to be related to #134

**Comment by brechmos-stsci** [comment]
@drdavella and I just noticed that it seems Glue/Cubeviz is trying to send a message to specviz to delete the region but there is an error in the message passing/acceptance and the plot in specviz is not being deleted.

**Comment by kassin** [comment]
Yes, I get the same behavior.  Also when the region is deleted, the collapsed spectrum of the
entire cube (the one that shows up upon reading in the cube) is deleted (but the spectrum of the region is not).

**Comment by nmearl** [comment]
@kassin That is certainty a bug. Mind opening an issue?

**Comment by kassin** [comment]
New Issue #153 : When a region selection made on a flux image is deleted, the collapsed spectrum of the entire cube (the one that shows up upon reading in the cube) is deleted.

**Comment by drdavella** [comment]
Closing since glue has provided a right-click option for selecting and deleting ROIs since https://github.com/glue-viz/glue/pull/1515.
