### ISSUE TITLE
Specviz slider interaction with images

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#147]
The specviz viewer has a bar that can be moved that changes the images in order to tie the two together. The bar in the specviz viewer is not easily viewable.  It needs to be more clear that the bar in specviz can be dragged to change the images.

Maybe change the color of the bar to match the Slice Navigator slider color (??) or possibly just make the bar thicker to distinguish it. 

(This is a follow on from #51 which was closed as all the functionality was implemented and this is just tweaking).

**Comment by kassin** [comment]
When I move the bar (or the slice navigator), only the Flux cube is scrubbed through.  It would be nice if the error and DQ cubes were linked so that they are also scrubbed through.

**Comment by nmearl** [comment]
@kassin That is the expected behavior: all three should scrub. Using the latest from the cubeviz repo, I am seeing all three of them scrub when I drag the line in the SpecViz viewer.

**Comment by kassin** [comment]
@nmearl I downloaded the master and the scrub doesn't work in error or DQ.

**Comment by kassin** [comment]
When I load the new data cube I placed in /astro/3/jwst_da_sprint_testdata/IFU_datacubes/KMOS_Mason
the slider doesn't appear in SpecViz.

**Comment by brechmos-stsci** [comment]
I think there is a problem with the loading of that data file. I tried loading with merge and without merge and neither one of them came up properly.  With data that "works" the images should be loaded and displayed automatically in the image viewers. Cubeviz does not appear to do it with this dataset.

Ah, if I bring up cubeviz, hit "Open Data", select the file AND select KMOS as the filetype then things seem to be correct.  I see the data, I can move the slice navigator slider through the data and I see different slices.

So, it seems the "auto" importer does not recognize this dataset as a KMOS dataset. 

@kassin Try that and see if you can load the data and see the slices (as you expect). If that is the case then we need to modify the importer for this dataset.

**Comment by brechmos-stsci** [comment]
I am going to create another issue for this data in particular and we can work off that ticket for the data and keep this one to do with the GUI.

**Comment by drdavella** [comment]
@kassin @nmearl I also encountered the bug with scrubbing through all three components of the cube. I'll open a new issue to track it.

**Comment by brechmos-stsci** [comment]
This is now fixed.
