### ISSUE TITLE
SpecViz mouse position values should read out to "Pos:" 

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#152]
Currently "Pos: 0,0" in the lower left corner of SpecViz doesn't update when the mouse is moved.

**Comment by brechmos-stsci** [comment]
I fixed this in specviz and created a PR https://github.com/spacetelescope/specviz/pull/359

**Comment by brechmos-stsci** [comment]
This is now fixed as https://github.com/spacetelescope/specviz/pull/359 is merged into specviz. This will be "visible" when people update their specviz code (developers do a pull / testers use the update script after 4am tomorrow morning).
