### ISSUE TITLE
Deleting region selection removes main spectrum from specviz

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#153]
When a region selection made on a flux image is deleted, the collapsed spectrum of the
entire cube (the one that shows up upon reading in the cube) is deleted.

**Comment by drdavella** [comment]
@kassin I don't think this is any longer the case. Can you confirm so we can close this issue?

**Comment by drdavella** [comment]
@nmearl can you confirm that this has been fixed?

**Comment by nmearl** [comment]
It indeed has been fixed.
