### ISSUE TITLE
KMOS_Mason data loading

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#155]
There appears to be a problem with the loading of a KMOS dataset as noted in https://github.com/spacetelescope/cubeviz/issues/147#issuecomment-355370859. 

It seems the auto importer is not detecting it as KMOS. If I click "open" and physically choose KMOS then it seems to load correctly (https://github.com/spacetelescope/cubeviz/issues/147#issuecomment-355636394).

So, I think the auto-importer thing needs to be tweaked for this dataset.
  
cc @kassin

**Comment by drdavella** [comment]
This is an easy fix, but it highlights the heuristic nature of these data loaders. Unless there are published standards or conventions for the contents of FITS files coming from specific instruments, it's going to be difficult to use anything other than informed guesses for identifying files.

**Comment by kassin** [comment]
@drdavella Agreed.  But luckily there are only about 10-15 IFUs in operation (the ones no longer in operation are pretty obsolete, except for VIMOS).  I am working on getting a cube from each of these instruments.

**Comment by brechmos-stsci** [comment]
Test tag for @mbarsony.
