### ISSUE TITLE
Selecting ROI button (or other viewer toolbar button) unlinks viewer

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/cubeviz#156]
@kassin first mentioned this bug in #147. Here's the problem: clicking any other viewer toolbar button in a particular viewer automatically deselects the button that syncs viewers (which is enabled by default). This means that subsequent use of the wavelength slider will not affect that viewer the same way since it is no longer linked.

@brechmos-stsci and I will look into this issue more, but this may require changes in `glue`.

**Comment by kassin** [comment]
Tagging @astrofrog to get his thoughts

**Comment by drdavella** [comment]
@brechmos-stsci and I are working on another solution to this that won't require any changes to `glue`. Hopefully we'll have a PR shortly. If it's acceptable to everyone else, we can leave it at that.
