### ISSUE TITLE
allow the user to resize windows

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#157]
In playing around with CubeViz I kept wanting to resize either the image or the spectrum viewer to encompass my full screen (and I was working with a large screen). If users can resize windows and allow them to overlap, they can create custom "dashboards" to suit their particular workflow. That said, I imagine this is not something that is easily done? @astrofrog  do you have thoughts on this?

**Comment by drdavella** [comment]
This was also mentioned by @hcferguson in #116, and is currently being tracked in #304, so I will close this issue.
