### ISSUE TITLE
Add cubeviz builds to conda and conda-dev

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#163]
Need to check to see if it is included, and if not, find a proper way to include.

**Comment by drdavella** [comment]
cubeviz is in `conda-dev` but it doesn't currently seem to be reflecting the latest commits.

**Comment by drdavella** [comment]
This has now been resolved and is reflected in https://github.com/spacetelescope/cubeviz/pull/202.
