### ISSUE TITLE
Idea: have a checkbox in the moment map dialog to compute moments only over current spectral ROI

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#167]
This is an idea to make it easy to compute moment maps over single spectral lines - it's currently possible to define ROIs in the specviz viewer, and we already have a moment map dialog, so the idea is to just add a single checkbox in the moment map dialog that gives users the option to use only the current specviz ROI to compute the moment maps. This would be a minimal addition UI-wise but pretty useful functionality.

**Comment by nmearl** [comment]
I like this idea. It would help reduce duplication of functionality, because then we wouldn't have to implement a moment map gui operation within SpecViz.
