### ISSUE TITLE
Make it clearer how to move regions

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#170]
As discussed on the call, we can add more information to the tooltip for the selection tools to advertise the control-click to drag. However, there's also a 'bug' in glue which is that if I change selection and then change back and try and drag it doesn't work (it only works immediately after drawing a selection). I'll fix that upstream.

**Comment by drdavella** [comment]
https://github.com/glue-viz/glue/pull/1515 will make it easier to move regions.

**Comment by drdavella** [comment]
We now support simply clicking and dragging regions to relocate them.
