### ISSUE TITLE
Provide an easy way in the UI to create new regions and delete existing ones

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#171]
At the moment creating new regions and deleting them has to be done via the full glue UI in the left panel, so we need to think of a way to expose that to users. I'm a little reluctant to replicate the whole glue UI inside the cubeviz layout, so this will require careful thought.

**Comment by nmearl** [comment]
Would it be possible to extend the selection modes available to include adding/removing selection regions? Something like:

![selection_modes_example](https://user-images.githubusercontent.com/4141126/35121289-e6c5120c-fc68-11e7-9a78-53b3f004ea7b.png)

**Comment by astrofrog** [comment]
Yes, though we need to think how one picks which region to remove

**Comment by drdavella** [comment]
This is currently being addressed in https://github.com/glue-viz/glue/pull/1515. Personally, for deleting regions, I like the idea of right clicking on a region and getting a context menu that provides the option to delete.

**Comment by kassin** [comment]
Users like me like to hit the "delete" key. :)

**Comment by drdavella** [comment]
New region creation is now the default mode when making selections in CubeViz. It is also possible to delete existing regions by right-clicking on them and selecting `Delete` from the dropdown menu.
