### ISSUE TITLE
Moment Map Alpha 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#179]
Moment map alpha goes to default level when moment map is changed b/w orders.

**Comment by robelgeda** [comment]
Not sure if this is a bug

**Comment by drdavella** [comment]
Not exactly a bug, just a feature that hasn't been implemented yet 😉 

Do you think the alpha setting for each different overlay component should be remembered?

**Comment by robelgeda** [comment]
@drdavella Actually I think there should be a universal alpha setting.
