### ISSUE TITLE
Add display of units of flux image onto the image

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#183]
The images need to show the units the FLUX is in and have the ability to change based on units of wavelength.

cc @kassin

(A future, companion issue is the ability to *change*  the FLUX units https://github.com/spacetelescope/cubeviz/issues/184 but that is for later)

**Comment by brechmos-stsci** [comment]
@robelgeda Make the "look" and "functionality" similar to that implemented in https://github.com/spacetelescope/cubeviz/issues/99

**Comment by brechmos-stsci** [comment]
@robelgeda  Could this easily be added now that you have the flux units implemented?  I think maybe where the title is in the matplotlib window.  e.g., "FLUX"  could be ("FLUX [ergs/s/cm^2/A/spaxel]" with the units in smaller font)?  It would be appropriate for FLUX and ERROR types not DQ.  

Though maybe this could be incorporated with the FLUX unit change ticket.

**Comment by robelgeda** [comment]
@brechmos-stsci : This is easy, I think it might be best to display the units only on the title because we lose a lot of precious space in the status bar. 
CC: @kassin

**Comment by brechmos-stsci** [comment]
Completed #252
