### ISSUE TITLE
Add spectral-cube Version into Requierments 

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#187]
My colleague ran into the following bug when trying to smooth a JWST/NIRSpec data cube.
![screen shot 2018-01-24 at 4 11 16 pm](https://user-images.githubusercontent.com/11748049/35358135-9f251734-0123-11e8-9131-d12224e15330.png)

The data cube is here:
/astro/3/jwst_da_sprint_testdata/IFU_datacubes/NIRSpec_Level2/gain_scale_assign_wcs_flat_field_pathloss_photom_g140m-f100lp_s3d.fits

Note that the file name is not what users will typically see because we had to run the pipeline in a somewhat non-standard fashion.

@robelgeda @brechmos-stsci

**Comment by robelgeda** [comment]
@kassin : They did not update their `spectral-cube` package. We need to make it a requirement in the future. Lets leave this issue open until we add this to the requirements. For now, we need to ask them to clone and install the [master branch](https://github.com/radio-astro-tools/spectral-cube) of `spectral-cube`.

**Comment by brechmos-stsci** [comment]
@robelgeda I think this could be considered part of #182 that you are working on.

**Comment by robelgeda** [comment]
@brechmos-stsci @drdavella : Can we close this now that conda-dev is working?

**Comment by brechmos-stsci** [comment]
Agreed. This should now "not be an issue" if the proper installation method is used.
