### ISSUE TITLE
Open Dialog Box - More Info

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#190]
From @bethanjames:

"It wasn't clear where the data were going once you've loaded them in. Perhaps include a message/note within the ‘open’ dialogue box to tell that the data will be found in Data Collection on the left hand panel once read in."

I agree, this would be a good idea to add.

@brechmos-stsci

**Comment by brechmos-stsci** [comment]
The dataset in question `/astro/3/jwst_da_sprint_testdata/IFU_datacubes/MUSE/MUSE_CosmicHorseshoe_bjames.fits` was not readable by cubeviz but cubeviz was not showing that there was an error in reading.

**Comment by brechmos-stsci** [comment]
this should now be taken care of with PR #210
