### ISSUE TITLE
Switching from Multiple to Single Viewer

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#191]
From @bethanjames:

"When switching between multiple and single viewer, it should remember what you're looking at, i.e. if you're in the multi-viewer you should be able to click 'single viewer' to see your currently selected window in the single viewer. Then when you switch back to multi-view, keep with the current settings (at the moment everything gets reset)."

@brechmos-stsci @drdavella

**Comment by brechmos-stsci** [comment]
If the views are synced then everything should be kept up to date. So if you move the slice in the single viewer then the slice will be moved in the multi-view (if the views are synced). If the views are not synced then they can be moved independently.  

@bethanjames Could you give a little more info on what you mean by the "what you're looking at".  Also, "at the moment everything gets reset"?  Thanks!

**Comment by bethanjames** [comment]
I mean the slice that you're looking at, so the single viewer will be loaded with the slice that you're currently looking at, then vice versa. For the 'reseting', I found that when I moved to a slice in the single viewer, and then went to multi-viewer, it moved back to slice=0.
If the views are synced then it sounds like this may not be an issue - I was using a MUSE cube, which perhaps isn't working yet in CubeViz.

**Comment by drdavella** [comment]
@bethanjames I have considered implementing a feature where if you are in the split viewer mode, and you double click on one of the viewers, it will automatically bring up the current slice in the single viewer. Would that be reasonable?

**Comment by bethanjames** [comment]
Yes, that would be great. If you then moved slices in the single viewer, would it be synced with the selected window in the split-viewer?

**Comment by drdavella** [comment]
It could work that way. It might just be easier to do it the way that you proposed, and make sure that the single viewer always reflects the state of the currently selected split viewer.
