### ISSUE TITLE
How do you get back to a three window multi-viewer, if you delete one?

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#192]
From @bethanjames 

Title says it all:
"How do you get back to a three window multi-viewer, if you delete one?"

@brechmos-stsci @drdavella

**Comment by brechmos-stsci** [comment]
@bethanjames Can you clarify what you mean by "delete one"?  Are you deleting one of the three viewers so only two are visible (which I don't think is possible, though might be a bug or do you mean deleteing a named tab?

If you can put a screen shot up here that might be helpful.

**Comment by bethanjames** [comment]
I deleted a dataset from the 'data collection' list, while it was loaded into the viewer, which then  deleted one of the viewers. I think it happened because the extensions weren't merged when I read the datasets in.

**Comment by drdavella** [comment]
I don't think we have accounted for this scenario, but we can look into it.
