### ISSUE TITLE
Acceptance Criteria

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#2]
- [x ] Load MANGA, NIRSpec, and MIRI data cubes.
- [x ] For flux units, check for default in fits header and allow editing. 
- [x ] Display the median stack

For the MANGA data cube:
- [ ] Display a given wavelength or wavelength range.  Note that the wavelength scale on the MANGA cube is in log.  This involves creating a custom viewer.
- [x] Plot a 1D spectrum of a given aperture ~~and its errors~~.  Show the spectrum ~~and the errors~~ at the same time with the option to unplot/replot the errors.  ~~For now use specview and the command line to do this.~~
  - [ ] ~~TBD:~~ Incorporate specview into Glue
- [ ] Fit an emission line in this spectrum and display the results.
- [ ] Fit multiple emission lines and display the results
- [ ] TBD: For a given emission line in the cube, fit a Gaussian to each spaxel where there is signal in the emission line. 
- [ ] Develop an python notebook with smoothing capabilities, simple multi-dimensional math, and slicing.

**Comment by stscieisenhamer** [comment]
Couple of glue issues for discussion with T.Robitaille:
1. There is no concept in glue for "flux units", or general voxel units. I've put in issue glue-viz/glue#652
2. Being able to drag selections about, issue glue-viz/glue#651
