### ISSUE TITLE
Add tests for data factories

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#227]
As discussed during this sprint, we need tests of the data factories in cubeviz. Rather than including full files in the repository, I suggested on one of the calls taking existing files and keeping only a subset of channels, but leaving everything else untouched - this should make it possible to have FITS files that are only a few hundred kB at most.

**Comment by brechmos-stsci** [comment]
@drdavella We should talk about how to store IFU FITS files for testing.  We did talk a little but should come up with a plan, even in the interim so I can add some tests for some basic cubes.

**Comment by brechmos-stsci** [comment]
@astrofrog and I talked. I am going to send him some of the files, he is going to create cutouts but with the same HDU header formats so that we can use these for testing.

There are two datasets I am checking on to confirm they can be made "public".

**Comment by brechmos-stsci** [comment]
@astrofrog , if you want to include the manga data, first, in a PR just to get it up here, go for it. The manga data is publicly available (https://www.sdss.org/dr15/manga/marvin/). Then we can add to the PR when we know about other data we can use. (Or we can wait, a few days, no prob)

**Comment by brechmos-stsci** [comment]
I talked with @bethanjames  and she is fine with us using the SINFONI data for data loader testing.
