### ISSUE TITLE
Slider in Plot Options 2D Image box does not Update the Slice No./Wavelength in CubeViz

### ISSUE THREAD

**Issue by mbarsony** [spacetelescope/cubeviz#230]
When I hit "Show Viewer Options" to open the Plot Layers 2D Image control panel, and play with
the Slider at the very bottom, which runs through image slices/wavelengths -- the wavelengths are
correctly displayed, but the corresponding slice number/wavelength in CubeViz does not update. @kassin @drdavella

**Comment by drdavella** [comment]
@mbarsony thanks for reminding us about this issue.
