### ISSUE TITLE
Use Case: Measuring line ratios from different spatial regions in a datacube

### ISSUE THREAD

**Issue by mbarsony** [spacetelescope/cubeviz#234]
Example science goals:  1. Determination of  excitation conditions as a function of position in a protostellar  molecular outflow, 2. Determination of star-formation rates from different emission regions in a red-shifted galaxy,  3. Determination of line column densities along different regions
in a source

  It is assumed that 
    1.  Ingested data have been: dark-subtracted, flat-fielded, and flux- and wavelength
calibrated
     2.  The background  (either from a dedicated background observation or from
source-free regions within the datacube) have also been: dark-subtracted, flat-fielded, and flux- and wavelength calibrated

   within CubeViz we should then be able to:

 a.  Re-do a proper flux-calibration for an extended (as opposed to point source) illumination pattern
(or, allow improved flux-calibration over default pipeline processing which may not properly
account for extended sources)

  b. Allow proper background subtraction to be performed for the entire cube using the 
          dedicated background observations, or, selected source-free regions within the datacube

  c. Fit a continuum to user-defined spectral regions (or the entire spectral range)
 in SpecViz for a selected spatial region

 d. Allow subtraction of the continuum fits from c.)  for user-designated spectral regions (lines, presumably) for measurement of line emission (or absorption) strengths

    e. After all of these steps have been carried out, we are ready to measure line fluxes (either in
absorption or emission) of user-selected  spatial regions within a user-specified wavelength range

    f.  It would be fantastic to be able to write our the measured results to an ascii (machine-readable) file, along with the input parameters used to derive the outputs.
@kassin

**Comment by kassin** [comment]
Fantastic!  Mary, we will work towards this use case.  

Note that we will assume 1 and 2, as suggested, above.  Likely we will also need to build "pipeline helper tools" to iterate with pipeline procedures, but I haven't even seen the pipeline yet!
Also note that the flux calibration will be applied to your data by the pipeline (step a).  Similarly step b will also be performed by the pipeline.

There are many small steps that we will break this up into, and we will make sure there is an "issue" for each.  For example: selection of spectral regions (step c), continuum subtraction (step c), selection of spectral + spatial regions (step c), measurement of line fluxes for selected spatial regions (step d), and writing out of results and procedures followed (step d).

**Comment by drlaw1558** [comment]
Have been trying to follow these threads, though not doing well on responding.  Your comment "I haven't even seen the pipeline yet" jumped out at me though as something that should be addressed asap.  The IFU-specific sections of the pipeline (CALSPEC3) are under particularly heavy development for build 7.2 over the next few months, but much of it is already in place.

I suggest setting up a meeting with the CCWG (contact Karl) to close the loop on pipeline helper tools and who has what ideas about them.  I have some that exist as vaporware in my head.

**Comment by kassin** [comment]
That would be awesome.  I'm currently away, back 3/5.  I'll contact Karl.

**Comment by brechmos-stsci** [comment]
Added to workflow page https://innerspace.stsci.edu/display/DATB/Workflows and so closing here.
