### ISSUE TITLE
Create release workflow

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#255]
We need to document a release workflow.  Partly so we are ready for April but also future releases.  Things we should document:  tagging in github, release names, uploading to pypy / conda places.  

Probably best to document on the Wiki so we can repeat in the future as needed.

**Comment by hcferguson** [comment]
Is there a workflow we can just copy from another project?

**Comment by brechmos-stsci** [comment]
Basically, yes.  @drdavella has been working on the ASDF release workflow and we will use what he has learned from it.  We can also talk to Joe/Matt as well.  What we could do is document and then request for comments from you, Larry, etc too.

**Comment by drdavella** [comment]
A draft of the release procedures has been posted here: https://github.com/spacetelescope/cubeviz/wiki/Release-Procedures

Someone should try it out independently (short of actually publishing the package) to make sure that it makes sense. Comments/feedback are welcome.
