### ISSUE TITLE
Document requirements for data cubes to load into cubeviz

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#256]
Write up what the minimum requirements are for loading data into cubeviz.

**Comment by brechmos-stsci** [comment]
@kassin is setting up a meeting in order for us to discuss what the minimal requirements should be

**Comment by brechmos-stsci** [comment]
Also, for now, https://confluence.stsci.edu/display/~crjones/Cubeviz+Data+Files is the place to check and see which cubes cubeviz will load (or not load).

If there is a cube you have, not in that list, that works or doesn't work, please email crjones@stsci.edu with a location of the cube and I'll add it to the list.

**Comment by javerbukh** [comment]
@brechmos-stsci @kassin
