### ISSUE TITLE
Have x-axis in image viewers default to hh:mm:ss when that axis is RA

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#269]
This is just a reminder that we need to fix the default format for Right Ascension to be in hours instead of degrees. I've started working on this.

**Comment by astrofrog** [comment]
This has now been merged into Astropy: https://github.com/astropy/astropy/pull/7215 and will be available in Astropy 3.0.2 once it's released.

**Comment by brechmos-stsci** [comment]
Already fixed by @robelgeda
