### ISSUE TITLE
Charlotte's workflow

### ISSUE THREAD

**Issue by charlottenosam** [spacetelescope/cubeviz#270]
I usually use QFitsView to explore KMOS cubes. I have 2 use cases described here so I below I list my 2 typical workflows:
1)  Spatially resolved z~1 galaxies with bright optical emission lines, sometimes continuum and rough specz from WFC3 grism data, so I'm usually just flicking through them to find the lines. 
2) Unresolved z>7 galaxies to look for very faint Lya emission... Some with tentative grism detections

**z~1 bright emission line galaxies workflow:**
- Open fits file and immediately collapse over a large/the entire wavelength range. KMOS has some astrometry problems so the objects aren't always centered, so I need to find them in a nice 2D image to start
- Clip pixel values to ~99% to remove spurious features (usually at the cube edges)
- I might need to crop the cube spatially if the edges really aren't good
- Once I know where the object is spatially, make a spatial aperture/region and plot the 1D spectrum in that region
- Zoom into the 1D spectrum to look at the lines and get good specz
- Plot the 2D emission maps collapsed over lines
- Step through the lines in wavelength pixels (or make a linemap over a few wavelength pixels) to look for velocity structure
- I then use my own code to make 2D velocity and velocity dispersion maps, inputing the redshift and emission line of interest, and make publication-ready figures.

**z>7 faint Lya emitter galaxies workflow:**
- Divide data cube by noise cube to get S/N cube
- Smooth spatially to do a 'matched filtering' (sigma ~ the seeing) and spectrally (FWHM ~ 10-15A typical line width for these types of sources)
- Select a PSF sized region in the centre of the cube (then repeat with different central positions)
    + Look at 1D smoothed S/N spectrum and look for peaks above S/N = 5
    + Collapse 2D map around any promising peaks to look for emission

**Comment by brechmos-stsci** [comment]
Both of these were added to the page https://innerspace.stsci.edu/display/DATB/Workflows.
