### ISSUE TITLE
Collapse cube wavelength range bug

### ISSUE THREAD

**Issue by charlottenosam** [spacetelescope/cubeviz#282]
**v0.1.dev534**

When trying to use the Data Processing / Collapse Cube to collapse a cube along wavelength axis between 2 wavelength values I get the following error message:
![collapsecube](https://user-images.githubusercontent.com/5003032/37220888-df1b8b90-237c-11e8-8cba-9b0dd68f3c9d.png)

If I switch to Region: Indices, or if I select a region in SpecViz, and then use Collapse Cube, there are no problems.

**Comment by brechmos-stsci** [comment]
Need to display units in the Start and End Wavelength labels.

**Comment by brechmos-stsci** [comment]
The GUI has been completely redone so closing this.
