### ISSUE TITLE
Image display of RA / DEC units on axes

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#287]
The RA default units show on the image x-axis either should not be deg min secs by default (and should be  hours, minutes, seconds) OR we need to make it use whatever is specifically defined in the file.

This is related to a ticket opened up by @astrofrog https://github.com/astropy/astropy/issues/7209.

**Comment by astrofrog** [comment]
I mentioned to @robelgeda how to fix this temporarily, this requires doing:

```
ax.coords[0].set_major_formatter('hh:mm:ss.ss')
```

Next week I'll finish up the Astropy pull request, but we need a workaround in cubeviz anyway since astropy 3.1 will only be out late this year.

**Comment by robelgeda** [comment]
Ah I will add a temporary fix to this then.

**Comment by brechmos-stsci** [comment]
@robelgeda When you do, please post a pic here of the axes of 1 image and let's confirm that it looks correct and tag @kassin and Mary

**Comment by brechmos-stsci** [comment]
This is now fixed based on #292
