### ISSUE TITLE
(New) update script for testers

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#290]
The update script was based on the astroconda-dev package system that builds packages from each repo's master environment. 

There appears to be a continuum of types of users of cubeviz.  Developers who will likely use master of each repo (or something close to it). Testers who we want to use specific, reasonably new, versions of some repos and then end users who will use, essentially tagged versions of repos.

For the testers, we need to setup an environment that has specific versions of the "big 6" repositories: cubeviz, specviz, specutils, spectral-cube, glue and astropy.  Some of the repos are fast changing and we may not necessarily want the master version for the testers to do their testing.

So..... I am going to update the update script (it's a meta thing) that will pull down and run a script that has specific commit hashes in it in order to lock the testing environment to what *we* want. This way we can test it beforehand and we will know exactly what version of the "big 6" they are at.

cc @kassin @drdavella

**Comment by kassin** [comment]
Thank you Craig.  This is the best solution.

**Comment by brechmos-stsci** [comment]
> This is the best solution.

Well, not sure about about "best".  It is "a" solution :-)
