### ISSUE TITLE
Region selection issue when multiple datasets loaded

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#299]
@smei100 ran into issues with region selection when she had multiple data sets loaded

**Comment by drdavella** [comment]
@kassin @smei100 please see #302 and discuss whether what I have proposed is reasonable.

**Comment by brechmos-stsci** [comment]
I renamed the ticket to remove "workflow" and moved it more toward regions and multiple datasets. Currently, cubeviz does not allow multiple datasets and so this ticket really is a future request type of thing. So, I'll leave it open.
