### ISSUE TITLE
Specviz spectral plot display when region selection and multiple flux cubes

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#301]
There is a bit of a question of what to show in specviz if we have mulitple flux cubes in cubeviz and a region showing on the cubes.

For example, if we have a FLUX cube and spatially smooth it. Then we draw a region in an image viewer.  Then... I suspect we want to see multiple spectra in specviz corresponding to the region applied to each FLUX or FLUX derived cube.

@kassin @drdavella

**Comment by kassin** [comment]
Is this incorporated in #299 ?

**Comment by brechmos-stsci** [comment]
Not really, #299 is related with data loading, should it be possible to have two copies of the same data loaded etc.  

This ticket is strictly to do with display of spectra from two related FLUX datasets (for example the original FLUX and a smoothed version).

**Comment by hcferguson** [comment]
Need to check what the behavior is once we link to the new SpecViz, and decide if we are happy with that.

**Comment by SaOgaz** [comment]
Reviewed current version, has product owner (@hcferguson) approval for now for current behavior.
