### ISSUE TITLE
Support a more flexible layout for cube viewers

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/cubeviz#304]
It would be nice to untie ourselves from a fixed three-viewer layout and to allow users flexibility in creating/removing new viewers as necessary and positioning viewers wherever they want.

See https://github.com/glue-viz/glue/issues/837 for upstream changes that could help us with this.

**Comment by kassin** [comment]
"free the viewers" ;)

**Comment by astrofrog** [comment]
I like the way Jupyter Lab deals with customizing the layout:

![flexible](https://user-images.githubusercontent.com/314716/37453117-01fb047e-2837-11e8-859c-e20ab6c39e89.gif)

It'd be nice if we could come up with a way to do it in Qt.

**Comment by drdavella** [comment]
As @hcferguson mentioned in #116, we should also provide an option allowing a viewer to fill the current canvas.
