### ISSUE TITLE
Overlay should not be shown by default, 2D component should popup initially

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#309]
When the collapse cube or moment maps are calculated, the overlay should not be displayed, but the 2D component should be displayed by default (maybe in the active viewer / or first viewer).

**Comment by brechmos-stsci** [comment]
@robelgeda if you have a little space, could you take this on?

**Comment by drdavella** [comment]
I'll take this one on if @robelgeda doesn't mind. It's a good excuse for me to refactor these tools, which I've been planning to do anyway.
