### ISSUE TITLE
Collapse cube sigma clipping interface

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#314]
@smei100 brought up a question about the sigma clipping for the collapse cube. The upper and lower clipping values were not clear.  She would prefer to have just a single sigma value to clip from.  

@charlottenosam also brought up the idea that clipping based on SNR might be helpful too.

As a slight aside, we might want to check the wavelength values and give a hint as to why a value did not work and/or suggested values.

**Comment by brechmos-stsci** [comment]
cc @kassin

**Comment by hcferguson** [comment]
Having the ability do specify separate upper and lower limits is sometimes useful (more so for CCD data than IR data I think). I agree a single sigma limit is more common and usually more defensible. 

Clipping based on SNR is an interesting idea. The simplest implementation is to treat the flux image as "signal" and get the "noise" from the error image. Another possible implementation if the error array isn't available is to allow (or to allow the user to override it) is to allow the user to create an ROI for a "noise" region and use the standard-deviation there for the noise. Of course they could do that themselves and write down the value and use it as "sigma" in sigma clipping, but this would save them that step.

**Comment by brechmos-stsci** [comment]
I suppose we could change the interface to have the standard sigma clipping (single value) as the basic option and then provide an advanced button that shows the astropy sigma clipping interface which we currently have.

**Comment by brechmos-stsci** [comment]
@kassin @hcferguson   I am almost done the collapse cube interface.  There are three options for collapsing: 1) no sigma clipping, 2) simple sigma clipping (one sigma value), and 3) astropy sigma clipping as was in there previously.

The simple sigma clipping was requested by Charlotte or Simona (can't remember which).  Is there an astropy function to do simple sigma clipping?  Or can I use the `astropy.stats.sigma_clip` with sigma=N, sigma_lower=N, sigma_upper=99999, iters=1 or something like that?  

I want to implement what is typical in the field and can document in the UI.

**Comment by hcferguson** [comment]
@brechmos-stsci For simple sigma clipping in option (2), I  would suggest just using the ```astropy.stats.sigma_clip``` with sigma=N and the astropy defaults for the rest of the options. If people want to tweak the other options, it's not too much to ask them to use the full interface of option (3) which should will let them tweak things like ```items``` and ```cenfunc``` as well.

**Comment by kassin** [comment]
I agree with Harry.  But we should state that these are the astropy default options so the user knows where they came from and where to look for documentation.

**Comment by brechmos-stsci** [comment]
Ok, and to be completely clear the typical procedure would be something like:
```
>> d = f[1].data
>> d1 = sigma_clip(d[100:400], sigma=3)
>> d1_sum = np.sum(d1, axis=0)
```

or

```
>> d = f[1].data
>> d2 = sigma_clip(d[100:400], sigma=3, sigma_upper=5)
>> d2_sum = np.sum(d2, axis=0)
```

[assuming 100:400 is what we are collapsing over and "sum" is the operation]

I just want to be sure this is what the typical procedure would be.

**Comment by hcferguson** [comment]
Yes, that order of operations makes sense.
