### ISSUE TITLE
Save Data dialog looks like it will overwrite fits file

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#324]
The Save Data dialog looks like it will overwrite the fits file.  Maybe change the text on the "Ok" button or add text above it to say the next dialog will allow you to select the output fits file.

cc @kassin @astrofrog

**Comment by brechmos-stsci** [comment]
@astrofrog Will you be able to take a look at the save dialog and maybe make a couple of changes to the button etc?

**Comment by astrofrog** [comment]
Yes, I can work on this today. By the way I am going to create a 'glue-fixes-required' label so I can more easily track issues that require changes in glue.

**Comment by astrofrog** [comment]
Oops there is already a glue label :)

**Comment by brechmos-stsci** [comment]
@astrofrog I think we can close this given https://github.com/glue-viz/glue/pull/1636, correct?

**Comment by brechmos-stsci** [comment]
Discussed with @astrofrog and it is completed.
