### ISSUE TITLE
Plot Layers Color/Opacity Sync make not default

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#326]
The "Sync" button is default to sync, but should be default not to sync. That way when the user changes the color/opacity it won't do it for all 3 windows (not ideal)

![image](https://user-images.githubusercontent.com/18348847/37595932-e704ad9c-2b50-11e8-8368-01b37b512582.png)

@kassin

**Comment by brechmos-stsci** [comment]
There was another comment that maybe the "Sync" button should be deleted (@kassin) as there is no real use case for syncing the color/opacity.

**Comment by astrofrog** [comment]
Just to clarify, in glue there are use cases for the sync button, just not in specviz, so we could selectively delete it in cubeviz.
