### ISSUE TITLE
Plot Options - 2D Image limits not related to actual images

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#327]
The limits seem to have nothing to do with the actual images.  Should they be deleted or is this a bug that needs to be fixed. (from @kassin)

![image](https://user-images.githubusercontent.com/18348847/37596091-627b57fa-2b51-11e8-8576-e8430b136b0c.png)

So, it seems they are pixel values though might make more sense to be 0 to 74 (for example, in the manga cube) rather than -0.5 to 73.5

**Comment by astrofrog** [comment]
@brechmos-stsci - with e.g. FITS, integer pixel positions are at the center of the pixel, so the limits in the image viewer are indeed -0.5 to 73.5. Can you clarify what you mean by 'nothing to do with the actual images'? Do they not update when you zoom in/out? We could always remove that tab in the image viewer subclass we have in cubeviz, but I just wanted to make sure I understand first what exactly is wrong with them

**Comment by brechmos-stsci** [comment]
The comment was from Susan. 

I understand now that the interpretation is the integer pixels are at the center of the pixel.  They do work, just tested.

**Comment by brechmos-stsci** [comment]
I am going to close as I think it is a mis-understanding of the values rather than a bug.
