### ISSUE TITLE
Arithmetic calculates in cubeviz

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#328]
@astrofrog If the goal is to move to use the Glue "Derived Component Editor":
![image](https://user-images.githubusercontent.com/18348847/37596766-999f25c0-2b53-11e8-9a7b-d0efdfb3c869.png)

Could you change the menu "Arithmetic Operations" to go right to the "Derived Component Editor" (not the Add/Edit Components)
![image](https://user-images.githubusercontent.com/18348847/37596789-aa8c1488-2b53-11e8-8039-f25b140d5e62.png)

**Comment by astrofrog** [comment]
@brechmos-stsci - there is an issue open for this already: https://github.com/spacetelescope/cubeviz/issues/284 - could you re-post this comment there? I'll try and work on this today or tomorrow.

**Comment by astrofrog** [comment]
I'm working on this today

**Comment by astrofrog** [comment]
Preliminary work required for this: https://github.com/glue-viz/glue/pull/1637
