### ISSUE TITLE
Useful Spectral Flux Density Units

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#340]
**What are some flux units that you find useful?**

Currently implemented spectral flux density units:
<img width="167" alt="screen shot 2018-03-26 at 7 01 34 pm" src="https://user-images.githubusercontent.com/10345916/37937549-29f82408-3128-11e8-8950-d332b4d0f05a.png">

Currently implemented area units:
NB: We use WCS pixel scale to convert b/w `spaxel` and `degrees`
<img width="84" alt="screen shot 2018-03-26 at 7 02 16 pm" src="https://user-images.githubusercontent.com/10345916/37937575-47e8d534-3128-11e8-94d7-98b2ebcc1495.png">

Current GUI for conversions:
Input Unit (From header): `1E-17 erg/s/cm^2/Ang/spaxel`
<img width="438" alt="screen shot 2018-03-26 at 7 03 10 pm" src="https://user-images.githubusercontent.com/10345916/37937591-5b0a59bc-3128-11e8-8b6a-d8920b85a2a6.png">

**Does this look intuitive and/or useful? 
How can we improve on these?**

CC: @kassin @hcferguson  @mbarsony @charlottenosam @smei100 @drlaw1558 @nmearl

**Comment by drlaw1558** [comment]
Can we sort the options according to like types?  E.g., group Jy, mJy, uJy, etc?

Also, is there a particular reason the units in each are in the order they are?  I missed the erg/s/cm2/Angstrom option at first because of the unusual unit order.

**Comment by robelgeda** [comment]
Thanks for the feedback. They are alphabetically sorted now but I will fix that. I think the weird order in the units themselves is due to `astopy.units` and I will see if I can fix them.

**Comment by robelgeda** [comment]
@drlaw1558 : I made the edits as suggested. Thanks again for the feed back.

For `1E-17 erg/s/cm^2/Ang/spaxel`:
<img width="101" alt="screen shot 2018-03-27 at 4 50 44 pm" src="https://user-images.githubusercontent.com/10345916/37994319-2f1f78ac-31df-11e8-81bb-8e494aae49f3.png">

<img width="164" alt="screen shot 2018-03-27 at 4 50 59 pm" src="https://user-images.githubusercontent.com/10345916/37994320-2f2b1388-31df-11e8-91d9-7f9b1c93390e.png">

**Comment by robelgeda** [comment]
Updates to the UI:
<img width="402" alt="screen shot 2018-03-28 at 12 19 59 am" src="https://user-images.githubusercontent.com/10345916/38008649-cacd4b42-321d-11e8-9afc-05739b62c265.png">

**Comment by brechmos-stsci** [comment]
The flux unit changer is now merged (#339). Will close this and we can open another ticket if people come up with other units they want.
