### ISSUE TITLE
Glue slider and wavelength display does not respond to change in units

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/cubeviz#342]
![image](https://user-images.githubusercontent.com/2458487/38047001-1783b324-328f-11e8-83ae-6ab199196408.png)

![image](https://user-images.githubusercontent.com/2458487/38046986-0cc2010c-328f-11e8-9c7e-fa1d7dc154cb.png)

cc @astrofrog

**Comment by drdavella** [comment]
IMO an acceptable solution would be for cubeviz to hide the glue-specific slider and wavelength display...

**Comment by kassin** [comment]
I agree with @drdavella

**Comment by SaOgaz** [comment]
@drdavella can this issue be closed?

**Comment by drdavella** [comment]
No, this still doesn't work. I will reiterate what I said above, though, which is the easiest/most reasonable solution would be just to hide this slider.
