### ISSUE TITLE
1.0 Release DIscussion

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#351]
We are currently planning a (pypi) release of Cubeviz on April 30th.  This will be the 1.0 release.  

@drdavella  and I were going through the Cubeviz specific release steps we had set out in the wiki and wanted to see about release schedules for our dependencies Glue, Spectral-Cube, and Specviz.

Glue (@astrofrog ):  Obviously we are super dependent on having something close to the newest version in PyPi so when we do a `pip install cubeviz` we can pick up the newest glue.

Specviz (@nmearl ):  Again, obviously we are going to be very dependent on Specviz being newest in PyPi. 

Spectral-Cube (@keflavich): I think the current version of 0.4.2 in PyPi will be fine as it has the spatial and spectral smoothing merge.  I don't think we need the `bnok` merge that was more recent.  Though, if you were planning a new version...well....

Spec-utils (@keflavich, @nmearl ): The current version we are pegged to is the tag `legacy-specutils` because of things breaking in specviz if we try to use the newest spec-utils (as I remember).  So, to be cleanest we may want to peg our release to use 0.2.2 currently release (very old) version and make sure it works. 

Astropy: We should be fine at the newest release.

So... given all this, @astrofrog  and @nmearl , do you think you would be able to do a release of Glue and Specviz around April 20 - 22.  This will give me enough time to create the release for Cubeviz and for us to do testing for the April 30th release.

Please tag anyone else you think might need to know this or if I forgot a dependency.

@astrofrog @keflavich @nmearl @kassin @hcferguson cc @jhunkeler

**Comment by astrofrog** [comment]
I'll do my very best to release glue v0.13 by the end of April if not sooner!

**Comment by keflavich** [comment]
[v0.4.3](https://github.com/radio-astro-tools/spectral-cube/releases/tag/v0.4.3) of spectral-cube is out.  It has an important bugfix that allows reversal of the spectral axis

**Comment by brechmos-stsci** [comment]
It ended up being a 0.2.0 release and is now done, so closing this.
