### ISSUE TITLE
Slicer Navigator issue

### ISSUE THREAD

**Issue by leonardoubeda** [spacetelescope/cubeviz#358]
Step 1: open FLAMES_Haro11_L6_cubeerr_bjames.fits

This will not be recognized as a cube.

Step 2: open manga-7495-12704-LOGCUBE.fits

This is recognized as a cube but the slice navigator does not work.

**Comment by brechmos-stsci** [comment]
@leonardoubeda Where could I get a copy of the file in order to test it?

The step 2 appears to not be an issue any more.

**Comment by leonardoubeda** [comment]
I placed the file in

 /user/lubeda/craig/
