### ISSUE TITLE
Editing parameter values in SpecViz

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#367]
Issue from Swara:

Specviz model fitting: 
--> to fit Gaussian to absorption lines, we had to provide a constant to define the continuum level. But, if we changed the constant to modify the value in the "current models" parameter edit space, it did not get applied to the plot. We had to delete that model, and add the constant again with the new value. Basically, can't edit the parameter value in place to get it to be applied to the plot.

**Comment by nmearl** [comment]
I'm not seeing this issue. Is Swara seeing output in the terminal?

**Comment by nmearl** [comment]
> Hi Susan,
> 
> I was trying to reproduce the specviz isue to show at the skype telecon. But, looks like the problem has gone away. Now, it works fine. If I edit the constant in the current models window, and press enter, it gets applied to the plot. Not sure why that did not work yesterday.
> 
> cheers,
> Swara.
> 
> Swara Ravindranath
> JWST/NIRISS Instrument Scientist
> Space Telescope Science Institute
> 3700 San Martin Dr.
> Baltimore, MD 21218
> (410)-338-2427
