### ISSUE TITLE
Override user matplotlibrc 

### ISSUE THREAD

**Issue by charlottenosam** [spacetelescope/cubeviz#371]
I have a custom matplotlibrc which makes fonts in image viewer look funky:

![38182786-a44739f2-35f0-11e8-9861-9bcb326f0afe](https://user-images.githubusercontent.com/5003032/38432472-5fa4ef44-397c-11e8-9599-4ca700b151b1.png)

I suggest explicitly setting the font sizes for cubeviz viewers to override users' custom values.

**Comment by astrofrog** [comment]
@charlottenosam - this should now be fixed in the latest developer version of glue, so once you update the problem should be gone. Please re-open this issue if not!
