### ISSUE TITLE
Specviz no longer responds to flux units changes

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/cubeviz#386]
This is being tracked in https://github.com/spacetelescope/specviz/issues/392.

**Comment by javerbukh** [comment]
Solved in specviz 392

**Comment by nmearl** [comment]
I've been working on the reverse of this issue: having cubeviz respond to specviz flux unit changes. This is proving to be a weird and circuitous issue. The machinery for changing flux data units in cubeviz is embded in the `QDialog` object; I can't access the logic without actually spawning the dialog. Currently, it's operating such that changes in the flux unit from specviz will spawn the (correctly) populated flux unit change dialog in cubeviz, but this is not ideal.

Also, the flux units in cubeviz is per-attribute of the cube (i.e. the `FLUX` can have difference units from the `IVAR`, etc). This seems really weirdly inconsistent (e.g. spectral axis unit changes effect the whole cube). Likewise, a single specviz plot has only one set of units. If the user has their `FLUX` and `IVAR` in different units in cubeviz, they will be displayed with the same units in specviz.

Something to think about for the future.

**Comment by hcferguson** [comment]
Sounds hairy. I'd be inclined to enforce common units on `FLUX` and `IVAR` in cubeviz, as specviz does. I can imagine that might be tricky to implement, given the interaction with glue.
