### ISSUE TITLE
Major Bug: Fast Slider

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#389]
#380 introduced a bug in which the same slice is redrawn over and over again (the temp index override no longer works). The slider does not work on my personal ubuntu machine.

**Comment by astrofrog** [comment]
Sorry about this, I think the fix is to change:

```
        if self.slice_index_override is not None:
            slices[0] = self.slice_index_override
```

to

```
        if self.slice_index_override is not None:
            slices = list(slices)
            slices[0] = self.slice_index_override
```

Does this fix it?

**Comment by astrofrog** [comment]
(basically the slices object is otherwise a special object that notifies the image viewer about changes to the slices)

**Comment by robelgeda** [comment]
Thanks @astrofrog !
