### ISSUE TITLE
Add tests for moment maps

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#390]
I just put in a PR for the new collapse cube that includes a `test_collapse_cube.py` file. That file you could use as a basis for a `test_moment_map.py` file. The `test_moment_map.py` file should be put in the same place as the `test_collapse_cube.py` and should contain essentially one test function that could be a copy of `test_regions()` that resides in `test_collapse_cube.py` maybe call the new function `test_moment_maps()`.

For the `test_moment_maps()` function you will need to:
1. Create the Moment Map GUI (simiilar to line 134 in the collapse cube call)
2. set the combo boxes to the right index (for let's say '0' for the first moment)
3. Get the 2d result from (similar to line 155 in `test_collapse_cube.py`
4. Calculate the first moment of the data (we can talk but basically it will be similar to lines 150 - 152 where you get the data, then you will have to call the spectral-cube moment map
5. Do the comparison similar to line 161

Ignore the region stuff in the `test_regions()` function. 

In the end, I think this should be done twice, once for the 1st moment and once for the 2nd moment.  We probably don't really need to do any more than that.

Chat me if you have any questions.

**Comment by javerbukh** [comment]
Tests are here: https://github.com/spacetelescope/cubeviz/blob/master/cubeviz/tools/tests/test_moment_map.py
closing issue.
