### ISSUE TITLE
Image Viewer PyTests 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#394]
-  Contour Tests:
    - [x] Settings 
    - [x] Preview 
    - [x] Other components 
- [x] Fast Slider Tests 
- [x] Fast Slider Indexing 
- [x] Title Tests 
- [x] Unit Display Tests
- [x] Smoothing Preview Tests 
- [x] Stat Box Tests 
- [x] Overlay Tests 
- [x] Indexing Tests

**Comment by astrofrog** [comment]
Can we set up coveralls or codecov on this repo?

**Comment by drdavella** [comment]
@astrofrog I was actually going to open an issue for that myself. I'll need to figure out how to do it directly since the astropy test runner has been giving us problems. I'm guessing `glue` has an example?

**Comment by drdavella** [comment]
Closing since all associated issues have been addressed.
