### ISSUE TITLE
Resolution Problems

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#408]
I got a loaner laptop and noticed that the text wrap is not working properly. This may be related to the font ticket from a long time ago.
<img width="304" alt="screen shot 2018-04-19 at 2 53 23 pm" src="https://user-images.githubusercontent.com/10345916/39012193-b962980a-43e1-11e8-8a3f-55486b4b088c.png">

**Comment by robelgeda** [comment]
Actually this block of buttons is taking up a lot of space:
<img width="1436" alt="screen shot 2018-04-19 at 2 58 19 pm" src="https://user-images.githubusercontent.com/10345916/39012352-35f05c40-43e2-11e8-840b-093132a41539.png">

**Comment by robelgeda** [comment]
Here is what CubeViz looks like on a 1360 x 768 Ubuntu screen:
![cubeviz](https://user-images.githubusercontent.com/10345916/39849622-3b8095a4-53db-11e8-8baa-f67919cc7637.png)

**Comment by kassin** [comment]
oy
