### ISSUE TITLE
Create GWCSCoordinate Object

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/cubeviz#41]
In order to use `gwcs` from ASDF files, it will be necessary to implement a `GWCSCoordinate` class,  analogous to the existing `WCSCoordinates` class used for FITS. It will also be useful to implement a `coordinates_from_gwcs` or `coordinates_from_asdf` function, in parallel to the existing `coordinates_from_header` function used for FITS.

@astrofrog do you think this can be implemented here or does it actually require an upstream change in glue?

**Comment by astrofrog** [comment]
@drdavella - we can implement it here, then later consider whether to move it back up to glue.

**Comment by brechmos-stsci** [comment]
@hcferguson may depend on astropy gwcs implementation.
