### ISSUE TITLE
Compatibility with Python 2.7?

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#416]
At the moment, cubeviz doesn't import in Python 2.7. Is the lack of Python 2 support deliberate? If so, I would recommend adding a note to the installation instructions.

If the intent was to support Python 2.7 then we should add jobs for Python 2.7 and 3.5 in Travis.

**Comment by brechmos-stsci** [comment]
Currently we are not going to support Py2.7.  Unless there is a huge uproar that we need to I think there is enough momentum for forward movement on everyone using Python 3, I think we should focus on Python 3.5+
