### ISSUE TITLE
Release cubeviz on PyPI

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#417]
It would be good to have releases of cubeviz on PyPI since users who don't use conda might still want to use cubeviz (and PyPI is considered the official repository of Python package releases). For glue I don't list PyQt in ``install_requires`` but instead have a hard-check in ``setup.py``:

https://github.com/glue-viz/glue/blob/master/setup.py#L76

I think this is the safest approach as it ensures people get a proper error message if Qt is not installed.

**Comment by drdavella** [comment]
I'll try to take care of this next week, unless it needs to be done earlier.

**Comment by brechmos-stsci** [comment]
I did a release on pypi but @drdavella please ck it and make sure things are kosher with it.

**Comment by drdavella** [comment]
Looks good to me, except that I had to install `specviz` manually and I also had to install `matplotlib` using conda in order to take care of the "qt as a framework" thing. Not much we can do about that at the moment though.
