### ISSUE TITLE
Wave table wavelengths not being used

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#426]
It was pointed out, that at least for our manga data example we may not be using the correct wavelengths.  The manga data has a WAVE extension that has values that look like this:
![image](https://user-images.githubusercontent.com/18348847/39780412-2fbbdff0-52da-11e8-9e6d-75801a05c319.png)

But when I load up the manga data in cubeviz, the wavelength values "read from the file" result in a plot like:
![image](https://user-images.githubusercontent.com/18348847/39780435-41cc6a20-52da-11e8-8ea0-a1193cfb53da.png)

So, if the correct wavelength values are the non-linear ones in the WAVE extension, we don't seem to be using them.  

(This was part of a larger conversation about storing wavelength values in fits files.  But that discussion I will introduce in a different location that has more to do with "how best to store non-linear wavelengths in a fits file for IFU cubes".)

So, I *think* we are not interpreting the correct wavelengths from this manga file.  (0.2.1 coming soon?  :) )

@kassin @drlaw1558

**Comment by drlaw1558** [comment]
I'm not sure I understand; where is cubeviz not using this properly?  In the examples at http://cubeviz.readthedocs.io/en/latest/functionality/ the MaNGA wavelength solution is displaying properly.

MaNGA data cubes indeed contain the wavelength solution in the 'WAVE' extension for convenience, but this is the same (to an accuracy of about 10 fm) as what you get by using the header keywords to construct the wavelength solution.  The wavelength solution for log-format data cubes (MaNGA has both linear and log format) follows the Greisen+06 FITS convention in which lambda=CRVALi*exp(CDi_i*(p-CRPIXi)/CRVALi) where p is 1-indexed.

**Comment by drlaw1558** [comment]
As far as cube-viz functionality, we shouldn't be using the wavelength table values when reading MaNGA data because the header keywords are (deliberately) not set in the manner that would trigger this behaviour (i.e., CTYPE of WAVE-TAB').

**Comment by brechmos-stsci** [comment]
@drlaw1558 Hmm... ok.  Going to look at this a little more, I am confused about something then.

**Comment by brechmos-stsci** [comment]
@drlaw1558 I looked at the data and at other IFU cubes and it seems things are working as expected.  Phew.  I am going to look into creating the IFU cube loader which will be a larger discussion about what we should expect etc.  But this seems to be a non-issue, here, so am going to close this.

cc @kassin
