### ISSUE TITLE
Flux units for Calculated Values

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#429]
What should the Flux units for the following be?

- [ ]  Spectral Smoothed 

- [x] Spatial Smoothed

- [ ] Arithmentic (2d map)

- [ ] Moment 

CC: @kassin

**Comment by robelgeda** [comment]
Solution: Use component_id to index the controller.

**Comment by hcferguson** [comment]
Spectral smoothed = Same as unsmoothed data
Spatial smoothed = Same as unsmoothed data
Arithmetic = perform the same operation on the units. This should be happening automatically already, right? Reporting the resulting units as text is easy.  Alas, it's tricky for making the visualization smart enough to deal with funky units that might result. Right now I don't think we have a great way of dealing even with the fairly common switch to log units in flux or wavelength (although I haven't tried it recently, to be fair).
Moments = Same deal -- perform the same mathematical operation on the units, which I imagine is already happening.

**Comment by hcferguson** [comment]
Test current behavior?

**Comment by brechmos-stsci** [comment]
Moment maps appear to have no units (?) at least for display:
![image](https://user-images.githubusercontent.com/18348847/52876654-d6466780-3125-11e9-84a8-43fb1c5a11fc.png)

Spatially smoothed has the same units as the original
![image](https://user-images.githubusercontent.com/18348847/52876702-fa09ad80-3125-11e9-86cd-1e90a17e5218.png)

Spectral smoothing appears to have no units, again, at least for the display:
![image](https://user-images.githubusercontent.com/18348847/52876778-33421d80-3126-11e9-8cea-67d1a017505d.png)

Arithmetic appears to not have units, I created a cube "2*{DATA}"  and the display is not showing units:
![image](https://user-images.githubusercontent.com/18348847/52876882-700e1480-3126-11e9-899d-3769ce2f8645.png)

Same thing with squaring the flux data "{DATA}*{DATA}", not displaying units:
![image](https://user-images.githubusercontent.com/18348847/52876922-959b1e00-3126-11e9-9dfa-cac717d732f3.png)

**Comment by brechmos-stsci** [comment]
So... for the Arithmetic Editor point above, we are using Glue's Arithmetic Editor (`glue.dialogs.component_arithmetic.qt import ArithmeticEditorWidget`). I talked with @astrofrog and he said the ArithmeticEditorWidget is unit-agnostic, so will not return units.  So, at least for this one, either we would have to do some work in Glue to make it unit-knowledgeable or do some post-hoc work in Cubeviz that would add units once a dataset (or datasets) is/are returned from Glue.  I think the first one would be easier, at some level, but definitely not for the very, very near term.

**Comment by brechmos-stsci** [comment]
Looking through the loss of units for the spectral smoothing probably isn't useful right now as the smoothing is done in specviz and then pushed back to cubeviz. So when the "new" specviz is complete this should be checked at that point.

**Comment by brechmos-stsci** [comment]
Going to create separate tickets for the three above that are not working:

arithmetic operations:  https://github.com/spacetelescope/cubeviz/issues/499 (and one in glue as it is the one that needs to implement https://github.com/glue-viz/glue/issues/1946)

moment maps: https://github.com/spacetelescope/cubeviz/issues/500

spectral smoothing: https://github.com/spacetelescope/cubeviz/issues/501

So, now that there are tickets for each of the others, I am going to close this ticket.
