### ISSUE TITLE
Create a DOI so CubeViz can be referenced in academic papers

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#430]

**Comment by brechmos-stsci** [comment]
Unless there appears to be a different or better way to do it, Zenodo has a neat way of creating a release in a GItHub package and then links it to a DOI. I did this for cubeviz and the 0.2.1 branch.  The link Zenodo gave me was https://doi.org/10.5281/zenodo.2538006.  The nice thing about this is that it links to a specific version of the package and not just the package in general.

(Currently the link isn't resolving for some reason, I have an email in to them.)

**Comment by brechmos-stsci** [comment]
This is now setup and with each release we should receive a unique DOI automatically. This is setup through the webhooks.

![image](https://user-images.githubusercontent.com/18348847/52638994-3b3d5b80-2ea1-11e9-961c-c33bffb09963.png)
