### ISSUE TITLE
Wavelength loading fix 

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#431]
So, in looking at some other questions about unit conversion, it was pointed out by @drlaw1558 that the Manga data representation in the specviz plot is not displaying the correct wavelengths.

After a discussion with @astrofrog it seems the IFU cube loader in cubeviz is stripping out a little too much information in the FITS file header that is being read in. In particular, the CTYPE3 'WAVE-LOG' is being converted to 'WAVE' and therefore the wavelengths are not being converted into the correct values.

I went through all the cubes in my directory and looked at the CTYPE3 value and found:
```
DATACUBE-HDFS-1.34.fits.gz ['', 'LINEAR', '', '']
DATACUBE_HDFS_v1p0.fits.gz ['AWAV', 'LINEAR', '', '']
GMOS_NGC4449_red_bjamesv2.fits ['LAMBDA', 'LAMBDA', '']
image13657_icuber.fits ['AWAV']
image23484_icubes.fits ['AWAV']
image23484_mcubes.fits ['AWAV']
image23484_vcubes.fits ['AWAV']
JWST-NIRSpec-IFU-GAL2136_CLEAR_PRISM.fits ['', 'WAVELENGTH', 'WAVELENGTH', 'WAVELENGTH']
kb170517_00151_icubes.fits ['AWAV']
kb170517_00151_mcubes.fits ['AWAV']
kb170517_00151_vcubes.fits ['AWAV']
KLASS_KMOS_COMBINE_SCI_RECONSTRUCTED_S2A_1261.fits ['', 'WAVE', 'WAVE']
manga-7495-12704-LOGCUBE.fits ['', 'WAVE-LOG', ]
manga-7495-12704-LOGCUBE.fits.gz ['', 'WAVE-LOG',]
MUSE_DATACUBE_HDFS_v1p0.fits.gz ['AWAV', 'LINEAR', '', '']
SCI-GUM43_SCI_COMBINED_7.fits ['', 'WAVE', 'WAVE']
SINFONI_CAS64_k_bjames.fits ['WAVE']
```

So, LINEAR, WAVELENGTH, AWAV, LAMBDA, WAVE-LOG and WAVE.  are the options that are coming up.  

@javerbukh Is going to implement a fix for this and we should do a 0.2.1 release as a correction.

Cc @kassin  @hcferguson

**Comment by drlaw1558** [comment]
Hm, things like ‘wavelength’ and ‘lambda’ I don’t believe are valid fits values for this keyword under the greisen convention.  We should check for valid forms first, and interpret as such before dealing with non-compliant values

**Comment by brechmos-stsci** [comment]
@drlaw1558 Agreed.  @javerbukh is going to go through the options and list out the ones that are valid and will be interpreted by cubeviz.  Then all others will be sanitized (such as wavelength and lambda).  

For this, before we merge, we would like you go to do a quick perusal once it is coded.  We will get back to you shortly.
