### ISSUE TITLE
Layout Look and Feel Upgrades 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#437]
Will return to this after SpecViz sprint. The layout can use some work to optimize the look and feel of the application. Please add ideas and screen shots here.

Improvement list:

- [x] Layout toolbar

- [ ] Axis label fonts and size

- [x] Order of image viewer toolbar tools (**Can't Be Done**)

- [ ]  Remove gap under the SpecViz viewer

**Comment by kassin** [comment]
nice

**Comment by astrofrog** [comment]
@robelgeda - note that for ``Axis label fonts and size`` you can set these in the bottom left panel under the 'Axes' tab - and if you want to change them programmatically for a viewer you can do e.g.``viewer.state.x_axislabel_size = 12``. The full list of properties you can change are:

```
    x_axislabel = DeferredDrawCallbackProperty('', docstring='Label for the x-axis')
    y_axislabel = DeferredDrawCallbackProperty('', docstring='Label for the y-axis')

    x_axislabel_size = DeferredDrawCallbackProperty(10, docstring='Size of the x-axis label')
    y_axislabel_size = DeferredDrawCallbackProperty(10, docstring='Size of the y-axis label')

    x_axislabel_weight = DeferredDrawSelectionCallbackProperty(1, docstring='Weight of the x-axis label')
    y_axislabel_weight = DeferredDrawSelectionCallbackProperty(1, docstring='Weight of the y-axis label')

    x_ticklabel_size = DeferredDrawCallbackProperty(8, docstring='Size of the x-axis tick labels')
    y_ticklabel_size = DeferredDrawCallbackProperty(8, docstring='Size of the y-axis tick labels')
```

**Comment by robelgeda** [comment]
Thanks! @astrofrog

**Comment by robelgeda** [comment]
Tested the above layout on Ubuntu and its saves us some space up top:
![selection_001](https://user-images.githubusercontent.com/10345916/40396845-34123d96-5dfd-11e8-9f7b-0d667949a608.png)

**Comment by SaOgaz** [comment]
This seems like a good place to put this comment.  In a test session @bethanjames commented that she found the locked in three image viewer windows odd when her dataset did not have three extensions.  Perhaps this is something that's already been discussed?

**Comment by brechmos-stsci** [comment]
This has been talked about a few times.  There is a related ticket https://github.com/spacetelescope/cubeviz/issues/304
