### ISSUE TITLE
Loading "big" cube is not permitted

### ISSUE THREAD

**Issue by saimn** [spacetelescope/cubeviz#439]
Sadly I cannot load my cubes because spectral-cube does not like "big" cubes !
On a laptop it makes sense, but not a machine with 500Gb of RAM :smile:, and the cube is not that big (I will open another issue about memory usage). So it should at least be possible to force loading a cube. 

![capture d ecran de 2018-05-23 10-15-32](https://user-images.githubusercontent.com/311639/40412632-2d31fc10-5e74-11e8-9ea9-7112dfbdc34c.png)

**Comment by brechmos-stsci** [comment]
This is likely more related to specviz as specviz uses/used SpectralCube as underlying storage. Specviz was completely re-written and will be incorporated into Cubeviz sometime in the next few months. We will have to re-evaluate at that point and open a ticket in Specviz if this is an issue.
