### ISSUE TITLE
use the same-sized extraction region for multiple cubes

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#441]
From Ben Sargent (NIRSpec and MIRI team member):
"In addition to my question about how to convert units, I also was wondering about being able to use the same-sized extraction region for multiple cubes.  For the MRS, the pipeline has given me 12 cubes, corresponding to the 12 sub-bands (4 channels, 3 disperser settings) of the MRS.  The pipeline will eventually be able to return a single cube covering multiple or all MRS sub-bands, but for now it just gives individual sub-bands.  I would like to use the same size extraction aperture for all cubes.  Is there a way for Cubeviz to remember the extraction aperture for one cube and apply it to others?"

**Comment by hcferguson** [comment]
This is a perfect use case for Glue workflows. Ignoring cubes for the moment, if one is dealing with selection in 2-D images, Glue already takes care of the WCS transformations to have the selection be the same in sky coordinates for the different subsets (provided they are already glued together). So I think the machinery for handling the geometry is there already. It's worth a test. Just read in two different cubes as separate data sets, link them, and try selecting a region.

What might not be there is convenient ways to stack the different sub-bands in to the same cube and have the selections work properly. Implementation could be trick here, and it probably makes sense to go through a few use cases and prioritize before diving into coding. Issues that come to mind include:

- The simplest implementation in the spatial direction would be to resample all the cubes to the finest spatial resolution. But that will give very highly correlated uncertainties in the lower-resolution channels.
- There are probably applications where it is best not to convolve the images to the same spatial resolution, and others where it is desirable to have them all convolved to the same resolution. That also introduces correlated uncertainties.
- If one doesn't resample in the wavelength direction, the dispersion solution will have discontinuous jumps where the cubes are pasted together. This may make things tricky if we are trying to handle this in a standard WCS. Possibly less tricky with gWCS. 
- The LSF will vary quite a bit with wavelength. We still haven't thought through how to propagate this info into the fitting machinery.
- It is probably best to provide the tools for stacking into one cube and matching resolutions outside of Glue/CubeViz.

**Comment by brechmos-stsci** [comment]
Workflow was added to https://innerspace.stsci.edu/display/DATB/Workflows
