### ISSUE TITLE
Contour of Moment Maps on Image Viewers

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#446]
Following up on todays tag-up. Right now, it is not possible to display a contour of moment maps over the data image. This is because the components containing the contour map live in a separate `Data` object and do not appear in the contour's list of components. I will look into ways of solving this when I return to CubeViz.

**Comment by hcferguson** [comment]
Is this already addressed? Need to test current behavior.

**Comment by brechmos-stsci** [comment]
I took a look at this... I created a moment map and then went in to the display-contour-map part and only the primary datasets are listed for display:
![image](https://user-images.githubusercontent.com/18348847/52876452-3e487e00-3125-11e9-8e2a-efdfb6841358.png)

**Comment by hcferguson** [comment]
Further clue: I made a moment map. It creates a component, which I can view as an image but not overlay as a contour map (it doesn't show up as an option for "other component" in the contour overlay menu). 

I see it as a plot layer, and when I highlight that, it tells me that it needs to be linked to the other data. So I do that. But, alas, it still doesn't show up as an option in the contour menu.
