### ISSUE TITLE
Active subset mode in glue

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#448]
I've recently added the ability in the developer version of glue to see the current active subset in the toolbar at the top (https://github.com/glue-viz/glue/pull/1797). For instance, by default at the start of a session, users will see:

<img width="471" alt="screen shot 2018-07-02 at 15 51 51" src="https://user-images.githubusercontent.com/314716/42172781-f16b835c-7e14-11e8-9af1-f8332575ff9e.png">

In 'vanilla' glue, once a subset is made, the active subset changes to the selection that has just been made:

<img width="457" alt="screen shot 2018-07-02 at 15 52 07" src="https://user-images.githubusercontent.com/314716/42172792-f93e7f9e-7e14-11e8-9834-e2b97ddcd8af.png">

For now, I've made it so that glue is backward-compatible with cubeviz - if cubeviz is used then the active subset remains 'None' by default unless the user explicitly changes it in the drop-down menu.

This issue is to let you know about the UI change, and also to check whether we still want the cubeviz behavior of always creating new subsets, or whether you would like to switch to the default glue behavior (that once a subset is made, it becomes the active subset, and future selections change the existing subset).

**Comment by SaOgaz** [comment]
Default behavior approved by product owner (@hcferguson) during test session, closing.
