### ISSUE TITLE
add unit test for JWST data

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/cubeviz#460]
JWST files:

MIRI IFU: jw10001001001_01101_00001_mirifushort_s3d_ref.fits 
det_image_ch1-short_s3d_ref.fits

**Comment by SaOgaz** [comment]
jw10001001001_01101_00001_mirifushort_s3d_ref.fits has some loading issues with the WCS.

**Comment by brechmos-stsci** [comment]
Could you post a file URL that could be used for the unit test?

**Comment by SaOgaz** [comment]
We don't have one yet. We still need to decide how we want to distribute these files.  Something we can talk about at the sprint planning session.

**Comment by brechmos-stsci** [comment]
Some of the discussion will be informed by ITSD and https://github.com/spacetelescope/style-guides/blob/master/guides/where-to-put-your-data.md too.

**Comment by SaOgaz** [comment]
Ignore files listed above,  the current test files we want to use are here: https://stsci.app.box.com/folder/69214387860
