### ISSUE TITLE
Add loader for MUSE data

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/cubeviz#48]
It appears that it will not be possible to detect MUSE cube data automatically, but it is still possible to provide a custom data loader that can be selected manually.

**Comment by brechmos-stsci** [comment]
Related to #73

**Comment by brechmos-stsci** [comment]
@kassin There appear to be two issues with the MUSE dataset that I have (DATACUBE_HDFS_v1p0.fits.gz).  

1. I am not sure the best header field to use to distinguish the MUSE data set.  Right now I have header['HDUCLASS'] == 'ESO' but that may not be right.

2. There is a problem loading the data into spectral-cube 
```
ValueError: No spectral axes found in WCS
```

So, I **think** something might be broken with it. 

@kassin Who can I contact about this dataset?

**Comment by kassin** [comment]
I got the MUSE cubes from http://muse-vlt.eu/science/hdfs-v1-0/  which was created by the instrument team and may not have the same formatting as the official ESO pipeline output?
I'll contact someone I know on the MUSE team about this.

The pipeline people at ESO should be contacted if they used the official pipeline.  This website on the MUSE pipeline
https://www.eso.org/sci/software/pipelines/muse/
sends me to contact usd-help@eso.org

**Comment by brechmos-stsci** [comment]
@kassin Please contact your person about the MUSE cube we have:
```
/astro/3/jwst_da_sprint_testdata/IFU_datacubes/MUSE/DATACUBE_HDFS_v1p0.fits.gz

ERROR: "No spectral axes found in WCS"
```

**Comment by kassin** [comment]
There is an updated version of this data cube: http://muse-vlt.eu/science/hdfs-v1-0/
But it currently is taking 7 hours to download...

**Comment by saimn** [comment]
Hi,
Glad to see support incoming for MUSE data cubes in cubeviz ! I produced some of the HDFS cubes from http://muse-vlt.eu/science/hdfs-v1-0/, so maybe I can help you ;)

The HDFS cubes have been produced a long time ago and with a non standard way, combining the individual cubes with [MPDAF](http://mpdaf.readthedocs.io/en/latest/). And they do not contain the usual ESO keywords, so they should not be used as a reference.

The standard way to proceed, using the official MUSE pipeline, will produce a cube containing all the useful ESO keywords, e.g.:
```
ORIGIN  = 'ESO-PARANAL'        / European Southern Observatory                  
TELESCOP= 'ESO-VLT-U4'         / ESO <TEL>                                      
INSTRUME= 'MUSE    '           / Instrument used.                               
HIERARCH ESO PRO TECH = 'IFU     ' / Observation technique
```
And now in MPDAF we also copy these keywords to the combined datacube, so relying on `INSTRUME` should be fine. There are other tools to combine cubes, but I don't know how they proceed (I can check if needed).

**Comment by saimn** [comment]
Also, I'm trying the latest version of cubeviz and saw the [muse loader](https://github.com/spacetelescope/cubeviz/blob/master/cubeviz/data_factories/configurations/muse.yaml) which requires a DQ extension. This will not always be true, there are cubes without DQ (where the missing/masked values are simply filled with NaNs).

**Comment by kassin** [comment]
@saimn Simon, glad to have you in the loop!  I was going to contact someone from the MUSE team, but didn't know who.

We will want users to be able to read in the public (older) MUSE cubes in addition to the newer ones.

Any chance you would be available today at noon Baltimore time (in 40 minutes) to join our tag-up over Skype?  If so, please send your Skype username.

**Comment by saimn** [comment]
Hi Susan, I can join (I will send you my username by email soon).
For the non standard cubes, it will be difficult to auto-detect if they do not have the needed keywords, but I guess it's fine if there is a way to manually specify the format ?

**Comment by kassin** [comment]
Thanks.  I couldn't find your email address. Mine is: my last name at stack.edu

**Comment by hcferguson** [comment]
@kassin It seems like we have some MUSE support now, but not for every flavor of MUSE cubes? I would suggest user re-testing of MUSE cubes of various flavors if there is time during the upcoming sprint, then closing this issue and opening new ones with details of specific failures.

**Comment by kassin** [comment]
I recommend keeping it open so we remember to involve saimn.

**Comment by SaOgaz** [comment]
During a test session with @bethanjames recently (using MUSE data) we also go some WCS header warnings. Filing this here since it seems like what really needs to happen is a some targeted MUSE data test sessions.
