### ISSUE TITLE
Windows tests and numpy multiarray import issue

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#481]
There was an issue (#479) with numpy multiarray import that we tried to track down. Given we have other work for the sprint and wanted to move on with that, we (@drdavella and I) put in a PR (#480) to move the Windows tests to `allowed_failures`.  

This Windows build/install needs to be looked into as to why the numpy multiarray is not installing properly for windows. Once this is fixed, the windows matrix needs to be moved out of the `allowed_failures` and back into the regular test section.

**Comment by astrofrog** [comment]
This usually happens when packages are installed that were build with a non-compatible version of numpy - for example if you installed a pandas wheel or conda package built against numpy 1.14 then installed numpy 1.11. This can happen if we mix pip and conda.

**Comment by drdavella** [comment]
This seems to have resolved itself (see [here](https://travis-ci.org/spacetelescope/cubeviz/jobs/499553888)) so closing.
