### ISSUE TITLE
Issues with fallback reader in cubeviz

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/cubeviz#493]
The following cube is a pretty common type of radio spectral cube:

https://astropy.stsci.edu/data/l1448/l1448_13co.fits

By default, if I load it in glue, the WCS gets parsed and the resulting glue data object has a ``.coords`` attribute that points to a ``WCSCoordinates`` instance.

When loading this into cubeviz, a different reader is used that apparently is not able to parse the WCS:

```
*******************************
Encounted an error during WCS parsing. Discarding world coordinates! 
ERROR 6 in wcs_units() at line 2588 of file cextern/wcslib/C/wcs.c:
In CUNIT3 : Mismatched units type 'time': have 'm', want 'm/s'.
*******************************
```

I'm not sure why that happens, as I haven't had a chance to investigate. However, the original cube does have units of m/s:

```
CUNIT1  = 'deg'                / Units of coordinate increment and value        
CUNIT2  = 'deg'                / Units of coordinate increment and value        
CUNIT3  = 'm s-1'              / Units of coordinate increment and value        
CTYPE1  = 'RA---SFL'           / Right ascension, Sanson-Flamsteed projection   
CTYPE2  = 'DEC--SFL'           / Declination, Sanson-Flamsteed projection       
CTYPE3  = 'VOPT'               / Optical velocity (linear)     
```

it would be good to make sure that cubeviz works with generic spectral cubes like this out of the box, so we should make our default reader more robust, or rely on the default one from glue.

**Comment by SaOgaz** [comment]
gwcs issue for bug: https://github.com/spacetelescope/gwcs/issues/207
