### ISSUE TITLE
Demo Storyboard

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/cubeviz#5]
1. Load NIRSpec and MIRI cubes
   - Scrub through each cube
   - Close them
2. Load MaNGA cube
   - Scrub through the cube and leave at H_a (~6840 A)
   - Keep open
3. Josh's RGB median (with added color toggling)
   - Close
4. Jonathan's ROI (decide where to place before hand)
5. Show that Jonathan's ROI selected area opens in Nick's SpecView
   - Fit an emission line (should be same as the one displayed in part 2, H_a)
   - Display results
6. Fit another emission line
   - Display results

**Comment by kassin** [comment]
7. Bring up a command line interface in Glue.  Load Ivo's smoothing script.  Smooth the cube in 3D. 
8. Display the smoothed cube (x,y).
9. Select a region and display the smoothed spectrum.

**Comment by ibusko** [comment]
Well, in reality I don't have any specific script to load. The notebooks use just stuff that is already available at the python command prompt. So in fact the only thing that Glue would be doing is to display the data object that resulted at the end of all that typing in the Glue iPython window.

**Comment by nmearl** [comment]
Some tasks to improve smoothing that ought be done today:
- [ ] Merge cube loaders.
- [ ] Grab the actual data from subset objects passed through messages (and create `Layer` object from this).
- [ ] Make sure SpectraViewer gets unit information from MaNGA headers (even if not from other data cubes' header).
