### ISSUE TITLE
Have a marker in the spectrum view of where the wavelength "slider" is and have their colors match

### ISSUE THREAD

**Issue by eteq** [spacetelescope/cubeviz#51]
From a discussion with @astrofrog : when the "slider" bar at the top of the cubeviz dashboard is present, there should be a corresponding vertical line (or ROI) in the spectrum view that is the *same color* as the slider bar button.  That's a critical cue to users that this is the same thing.

cc @drdavella @nmearl

A possibly-related question (although it might be a can-of-worms not worth worrying about right now): ideally you can also set spectral ROIs instead of a single wavelength bin.  How is that to be represented in the slider?  Regardless, the rule above of color-matching should be preserved.

**Comment by drdavella** [comment]
Not sure if this will end up falling to me or @nmearl but feel free to assign this issue to me if it makes sense.

**Comment by eteq** [comment]
Probably needs to be a little of both (@nmearl might need to do something on the specviz side?) but probably makes sense to assign it to @drdavella - I just added you to the repo with write powers, so I *think* that means you'll be able to assign yourself.

**Comment by nmearl** [comment]
If this lives in SpecViz, it's probably more efficient for me to tackle it.

**Comment by eteq** [comment]
A bit of both, I imagine - I'm not sure how much specviz work is needed to get everything sync'ed up, but the color-matching will require some work in the new cubeviz dashbaord @drdavella  and @astrofrog are working on, also.

**Comment by drdavella** [comment]
This has been implemented in #129, although the color doesn't match. I'm not sure that part is critical, but it would be useful to somehow make it more obvious that the specviz bar is tied to the wavelength slider.

Closing since the core functionality is there. A future issue can be opened to improve the UI if desired.
