### ISSUE TITLE
Image Viewer tests: Fast slider tests

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/cubeviz#510]
Part of #394

**Comment by javerbukh** [comment]
How is this different from `test_fast_slider_indexing` in cubeviz/cubeviz/tests/test_ui.py, line 258? @brechmos-stsci @drdavella

**Comment by drdavella** [comment]
It's possible that the existing test already addresses this so the issue can be closed. However, it seems like it would also be useful to have a test that calls `fast_draw_slice_index` in `cubeviz/image_viewer.py`.

**Comment by javerbukh** [comment]
Ok, since part of this issue is solved, I will put this at a lower priority than the other pytest issues. I will get back to this if time allows.

**Comment by drdavella** [comment]
While the function `fast_draw_slice_index` is not called directly in any tests, according to `codecov` it appears to be covered by the test suite (see [here](https://codecov.io/gh/spacetelescope/cubeviz/src/master/cubeviz/image_viewer.py#L656)), so I'm closing this issue.
