### ISSUE TITLE
Image Viewer tests: Title tests

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/cubeviz#511]
Part of #394

**Comment by javerbukh** [comment]
What is being tested here? @brechmos-stsci @drdavella @robelgeda

**Comment by drdavella** [comment]
I think the idea is to make sure the title in the `matplotlib` viewers accurately reflects the data that is being displayed:

![image](https://user-images.githubusercontent.com/2458487/53903019-8f56de00-4010-11e9-903c-d7b1fb19667c.png)

In this case, we want to make sure that the title ("018.DATA") corresponds to the data component that is being displayed in that viewer.

The test for this should be pretty simple: just make sure the expected title is being displayed at the start of the test, and then change the data being displayed and check the title to make sure it's updated appropriately.
