### ISSUE TITLE
Refresh the cubeviz wiki

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#517]
The cubeviz [GitHub wiki](https://github.com/spacetelescope/cubeviz/wiki) needs some scrubbing. 

There are some ancient demos. Some of the other links are broken. I'd suggest clearing out the wiki and put the updated stuff in the documentation, since the wiki's are harder to find.

**Comment by brechmos-stsci** [comment]
@hcferguson Here are my thoughts on each page:

* Home - leave it, but possible small cleanup
* 0.3 Beta Install Instructions - leave it for now as it will be helpful, but could generalize this later
* Alpha Testing instructions - delete it
* Default File Formats - delete it as the basic info could be found in the yaml files
* demos - delete it, very old
* Developer Information - leave it as there are notes there that are helpful
* FAQ - leave it, again, could be useful
* Github Branch Testing in a Conda Environment - leave it, useful for testers
* How to Run Tests - leave it, new and relevant
* List of CubeViz Features - delete it, should be in the readthedocs documentation
* MOS Tools Input Table Structure - delete it
* References and Resources - leave it, but I'll add a paragraph at the top to say something about "related tools"
* Release Candidate 0.2.0 - delete it
* Release Procedures - leave it as it is helpful for releases
* Testing Conda Recipes Locally - leave it as  I believe it is still helpful
* Use cases, test data sets, UI sketch - delete it, don't need it as we have an internal location for listing datasets we have

**Comment by hcferguson** [comment]
@brechmos-stsci 

I agree with your assessment.

Please keep the "Default File Formats" and "List of Cubeviz" Features for today -- or show me how to view the archived versions -- I'll try to work some of this into the docs. Then we can delete from the wiki so we don't have to maintain in two places.

**Comment by brechmos-stsci** [comment]
I made all the changes, emailed you a copy of those two pages (and then deleted them, but we can always get them back).  So, I am going to close this ticket now.
