### ISSUE TITLE
Make the cubeviz dashboard states be toggle-button driven

### ISSUE THREAD

**Issue by eteq** [spacetelescope/cubeviz#52]
From a sprint-driven breakout with @astrofrog: the dashboard design as of this writing has two buttons, one for tiling and another for "stacked" view.  This should be changed to a single *toggle* button that sets two distinct states that make the *header* bar look different.  To be very explicit on these states:

In stack mode:
There are two viewers, one the "image" mode, and the other the spectrum.  The flux/err/dq buttons are present as individual toggles, and they control both the "image" overlays, and whether or not the flux/err are shown in the spectrum (and for dq they determine whether or not bad-dq values are masked in the spectrum).  To "unlink" the spectrum from the image, you can use the standard specviz options, but when hitting the flux/err/dq buttons, it goes back to whatever the state should be with the relevant set of buttons are set.

In tile mode:
The flux/err/dq buttons should be greyed-out (or even not-visible, although if that's notably harder it's not worth doing right now). By default flux and err are turned on on the spectrum side, and user must use the specviz interface to turn those on or off.

A possible alternative is to have the flux/err/dq buttons be on in the tile mode, but have them toggle the lines in the spectrum. I think @astrofrog and I are mildly against that, but best thing is to just do user testing and see if they think the above proposal is confusing or not.

cc @drdavella @nmearl

**Comment by brechmos-stsci** [comment]
This has been re-worked and is completed.
