### ISSUE TITLE
Change pytest version comparison operator

### ISSUE THREAD

**Issue by pllim** [spacetelescope/cubeviz#53]
astroconda/astroconda-dev#69 should be fixed upstream here. c/c @jhunkeler

**Comment by pllim** [comment]
OK feel free to update the title. I was just copy-and-pasting. Is there a reason why it can't be `pytest>=3.1`?

**Comment by nmearl** [comment]
Not specifically, but historically `pytest` + astropy template has been pretty finicky. Pinning `pytest` version to one that we know works is really just a safety precaution to avoid failing builds in the future.

I'm just wondering why the conda build system can't handle equality operators, or if it's an issue with `pytest`'s version specifically.

**Comment by pllim** [comment]
Using `==` is too specific and will cause version resolution of other packages in the channel to conflict. Probably that's why. (My semi-educated guess.)

**Comment by drdavella** [comment]
I haven't been tracking this as closely as I should, but I think this was actually due to upstream issues in astropy when using pytest 3.2, but I think that has been resolved now.

**Comment by pllim** [comment]
Yes, `pytest>=3.1` should work now, based on what I see in the latest dev change log on astropy.

**Comment by brechmos-stsci** [comment]
@drdavella is this completed now?  If so, please close.

**Comment by drdavella** [comment]
Not yet. I believe we need to wait until the release of Astropy v2.0.3, which fixes this problem.
