### ISSUE TITLE
Spectrum in specviz not removed when corresponding cubeviz region deleted

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/cubeviz#531]
During a test session with @bethanjames, we had several regions selected.  She deleted one region, but the spectrum for that region was not deleted in the specviz plot window.  I also have a note that the "overly was not what was expected" but I'm not sure what we meant by that...

**Comment by brechmos-stsci** [comment]
@hcferguson This seems to be a bug in the cubeviz-specviz interaction and maybe should be fixed next week before the release.

I am not sure how much work this would be to fix, maybe @nmearl could weigh in on it.

**Comment by drdavella** [comment]
This was fixed. See https://github.com/spacetelescope/specviz/pull/680.
