### ISSUE TITLE
unclear wording in Export Data/Subsets popup

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/cubeviz#534]
One user found the wording "all data no subsets applied" to be confusing.  She wasn't sure what was meant by subsets.  Maybe we can add some additional wording here?

**Comment by brechmos-stsci** [comment]
This is down inside Glue (https://github.com/glue-viz/glue/blob/c8c7056bdc75f4cb55307bbc0f758003ab69285d/glue/app/qt/save_data.py#L63) so I think it might be best to open a ticket there in order to change the verbiage.
