### ISSUE TITLE
Units in MANGA file

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#537]
Cubeviz complains about the units in the MANGA test dataset: 
/astro/3/jwst_da_sprint_testdata/IFU_datacubes/manga-7495-12704-LOGCUBE.fits.gz.

```
Failed to add subset
'1E-17 erg/s/cm^2/Ang/spaxel' did not parse as unit: At col 17, Ang is not a valid unit. Did you mean aG, aN, ag, nG or ng?
```

There are various sub-issues here:

- The traceback shows that an exception occurred during the handling of the exception
  - Cutting and pasting the traceback from the details window doesn't work on my Mac
- The message in an error box ends with a question, but there are no hints to the user on how to answer that (and in this case "none of the above" is the answer)
- While cubeviz will successfully load this file, this warning message comes up every time you try to do anything with an ROI in the image viewer.

**Comment by brechmos-stsci** [comment]
This is something new that just started coming up after the cubeviz-specviz integration, though 'Ang' is not a valid unit. The question, I believe is coming from astropy.units (https://github.com/astropy/astropy/blob/de3933688433e22765b1bdffa175fcd954d691c3/astropy/units/format/utils.py#L152) so it is not a cubeviz specific question.

A couple possible solutions:
  * Don't load the dataset as the units can not be interpreted by astropy.
  * Add a conversion from 'Ang' to 'A' (angstroms) as part of the FITS file cleanup that has to happen anyway (and include the conversion as part of the FITS cleanup dialog that comes up so the user knows what happened)

Either way we probably need to catch that warning/question so it is not printed at all.

**Comment by drlaw1558** [comment]
Longer term I'll change the MaNGA data format to 'Angstrom' instead of 'Ang', but this won't impact publicly-available data for ~ 18 months.

**Comment by drlaw1558** [comment]
Done!
