### ISSUE TITLE
segmentation fault on Fitted Linemap

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#539]
Fitted a Gaussian plus Linear model in the specviz window then selected `Fitted lineman` under cube operations. The beach ball spun for a while before it gave the following segfault error:

```
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]
WARNING:astropy:The fit may be unsuccessful; check fit_info['message'] for more information.
[1]    52728 segmentation fault  cubeviz
```

I was using the NGC4151_Hband cube in /astro/3/jwst_da_sprint_testdata/IFU_datacubes/AGN_outflow.

**Comment by brechmos-stsci** [comment]
@hcferguson , is there more information? (e.g., longer traceback?) I suspect a specviz issue should be created for this and linked back to here as I think this is a specviz issue, not strictly cubeviz.
