### ISSUE TITLE
Bug: "execution aborted" error in glue terminal

### ISSUE THREAD

**Issue by javerbukh** [spacetelescope/cubeviz#543]
1. Open cubeviz
2. Press on terminal button
3. Run a command that will fail, like `session.app`
4. User will be presented with `ERROR: execution aborted` in the terminal window in glue and no error in the terminal window that opened cubeviz in the first place

**Comment by brechmos-stsci** [comment]
Try it in Glue, it might be a glue error and not cubeviz....

**Comment by astrofrog** [comment]
It’s a bug in ipykernel, downgrade to a version <5

**Comment by astrofrog** [comment]
By the way it will be fixed in ipykernel 5.1.1. I think the latest glue conda package should now include version restrictions for ipykernel.

**Comment by javerbukh** [comment]
Since this is not a cubeviz issue, should I close this?

**Comment by brechmos-stsci** [comment]
Not yet, as we are going to have to peg the ipykernel version from above for installation.
