### ISSUE TITLE
Specviz in a separate tab

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#547]
One can select a subset from the `Subsets` menu and then select the specviz viewer. The viewer will pop up in a separate tab. When I tried it after having already created a profile viewer in a separate tab, the specviz viewer opened in that tab. The pan controls worked but zoom didn't.

I closed the tab and tried it again with just the specviz viewer and the controls all worked.

**Comment by nmearl** [comment]
It sounds like this would solve itself if we remove the option to create the Glue profile views.
