### ISSUE TITLE
Invalid/irrelevant header value issues message

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/cubeviz#559]
When loading the test data cube that is packaged with cubeviz, I get the following message about header value issues:

```
Checking filename cubeviz/tests/data/data_cube.fits.gz

HDU cubeviz/tests/data/data_cube.fits.gz_0
    CTYPE1 is NONE, setting to RA---TAN
    CTYPE2 is NONE, setting to DEC--TAN
    CTYPE3 is NONE, setting to WAVE
    CUNIT1 is NONE, setting to deg
    CUNIT2 is NONE, setting to deg
    CUNIT3 is NONE, setting to um
    Setting HDU 0 EXTNAME field to cubeviz/tests/data/data_cube.fits.gz_0
```

I don't think this makes any sense. Why does the primary HDU need any of these keywords? All of these keywords are present in the two HDUs that contain the actual data, so there doesn't seem to be a problem with this file.

**Comment by saimn** [comment]
:+1: , I see this message with MUSE cubes, where the primary HDU has no data. See also #438
