### ISSUE TITLE
Readthedocs latest vs. v0.3

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#586]
Readthedocs shows the latest documentation when you ask for 'latest'....but the latest release of cubeviz is v0.3.0 and when you pull up the v0.3.0 docs on readthedocs it shows an older version.

**Comment by SaOgaz** [comment]
Looks like RTD is pulling the v0.3.0 from the v0.3.x branch... which does not have all the updates to the docs. For example see:

https://github.com/spacetelescope/cubeviz/commits/master/docs/index.rst
vs
https://github.com/spacetelescope/cubeviz/commits/v0.3.x/docs/index.rst

@brechmos-stsci did the v0.3.x branch not actually get all the commits from master?
