### ISSUE TITLE
Change wavelength range (and channel range) for subsequent operations in the GUI

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#59]
Imported from Trello https://trello.com/c/vCVkZp9N

**Comment by brechmos-stsci** [comment]
Needed for moment maps for most use cases ( @hcferguson )

**Comment by nmearl** [comment]
This sounds like it will require some GUI changes (i.e. input boxes for new wavelength ranges).

**Comment by kassin** [comment]
Related to #93

**Comment by kassin** [comment]
Crop the cube in wavelength space.

**Comment by kassin** [comment]
In speaking with some NIRSpec team members, I found two main use cases for this functionality.  

1. Removing the first and last few channels which are usually junk in ground-based IFU cubes (a common use case)

2. In spectra which have complex continua and emission/absorption lines, it can be helpful to measure continua locally (i.e., close to the emission/absorption lines of interest).  Therefore, a user might want to chop up a cube into smaller sections in wavelength and fit the continuum (and lines) in each section separately.

@hcferguson @brechmos-stsci @nmearl @drdavella

**Comment by hcferguson** [comment]
**Use cases involving 1-D wavelength and 2D spaxel selections**

I’m trying to get my head around the correction functional specification for these interactions:
* How immediate do they need to be?
* Are there visualizations that need to sync in “real time” as these are changed?
    * As the ROI is adjusted?
    * Only when the adjustment has “ended” (e.g. mouse release)
    * Only when affirmatively told (extra click or command of some sort needed)
    * Do do we need more than one flavor of this?
    * E.g. different modes — “disable real-time update mode” and “enable real-time update mode” toggled by hotkeys?  (sort of like : commands in vi?)
* Do the wavelength selections need to be shown in the spatial view or is it sufficient to have them displayed in the specviz ROI?
* How will users be able to get the exact ROI and spaxel selections output for use in scripts?

To assist in thinking about this here are some possible use cases:
1. Standard dashboard — 1D ROI
    * Seems to me fine here that the wavelength ROI only appears on the specviz window
    * The wavelength ROI has no effect in this view on the spatial visualizations
    * There could be a “crop in wavelength” button to create a new glue data object for the cropped data set. 
        * Cropping should be applied to err & DQ as well
2. Standard dashboard — 2D spaxel selection
    * Ideally the 1-D spectrum updates “in real time” as this is adjusted
    * If that’s not responsive enough, it’s fine to do this on mouse release
    * There’s no practical way to display the spaxel selection in the SpecViz window, so really one needs the overlay on the 2D image.
        * Should be able to toggle this on and off with a hotkey
3. Operation 1 — 1st moment
    * The first moment is usually used to make a velocity map. The output is a 2D image where the intensity encodes the velocity (usually blue for low velocities and red for high velocities).
    * One usually wants to select a small region of the spectrum centered on an emission (or absorption) line and then calculate the 1st moment for just that wavelength region over the whole cube.
    * One will often want to tune the wavelength selection looking only at some spaxels where the emission is strong, then apply that wavelength selection to the whole cube to make the final moment map.
    * Calculating moments *might be* fast enough to do this in real time as the wavelength ROI is adjusted. But it is fine to do this on mouse release. Also okay if it requires an additional command.
        * But a more refined approach to making the velocity map is to *fit* the line in each spaxel (having adjusted the wavelength ROI and continuum-fitting algorithm). That is likely to be too slow to update in real time. Even having this fire off automatically on mouse release could be irritating if it ends up being an operation that takes more than a couple seconds, since more often than not a mouse-release event isn’t the final choice.
        * Do we need a different behavior for the first time you measure a moment (where you may yet have the velocity map up in a graphics window) from subsequent times (where you might want some sort of immediate feedback)
1. Operation 2 — Line ratio map
    * In the simplest case here one has defined two 1D ROIs and is taking the ratio and displaying that in a 2D image. 
    * One usually wants to adjust these regions based on a small set of spaxels before applying to the whole map.
    * Calculating the ratio *might  be* fast enough to do this in real time.
        * But a more refined approach would fit lines and continuum in each ROI to compute the integrated flux in the lines and take that ratio.
        * There needs to be sensible treatment of “divide by zero” issues.
    * Same sort of concerns as for operation 1. This might be fast enough for real-time updates in the simple case but probably not in the more refined case.

**Comment by hcferguson** [comment]
And then the question is how do you associate a certain set of wavelength ROI's with a certain set of 2D "products" of the operation. Do you need to start over if you want to measure line ratios and make velocity maps on the same cube with different sets of ROIs? This isn't a big deal if "applying" the ROI operation always requires a command ".e.g. measure the 1st moment" or "take the ratio". But if you are adjusting the 2D visualization in real time, how do you know which one(s) to update and which ones to leave alone?

**Comment by kassin** [comment]
Thank you Harry.  We're working toward these use cases.  Some comments:

-Not sure we need (1) above where the 2D image doesn't respond to the spectral selection.
I want to select wavelength ranges of the spectrum and see the resulting "linemaps" appear in the 2D image in real time.

-I agree with (2) above.  The different regions selected in the 2D image should appear in different colors.  The resulting spectra should appear in SpecViz with the same colors.

-We should have the option of creating moment maps using the moment calculation in astropy, but most people will want to measure them by hand.  To do so, they fit the emission/absorption line
in each spaxel and create moment maps with the resulting fits.  For example, I fit a Gaussian to an emission line in one spaxel and then hit "apply all" to fit a Gaussian to the same wavelength range
in all the spaxels.

Users should have the option of applying their fit to selected regions of the 2D image, and not just "apply all."

The user should be able to inspect all the fits.
