### ISSUE TITLE
Problem with testing the last release in Python 3.9

### ISSUE THREAD

**Issue by pllim** [spacetelescope/cubeviz#598]
`pip install cubeviz` downgrades `pyqt5`, causing this message to appear when `mosviz` is also installed: `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. mosviz 0.3.1 requires pyqt5==5.12.3, but you have pyqt5 5.8 which is incompatible.`

Running `cubeviz` command gave me this error in a clean `conda` env with Python 3.9 after I installed `qt` from `conda`. I failed to install PySide from both conda and pip; not sure why.

```
$ cubeviz
Traceback (most recent call last):
  File ".../python3.9/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../cubeviz", line 5, in <module>
    from cubeviz.cubeviz import main
  File ".../cubeviz/__init__.py", line 38, in <module>
    from . import keyboard_shortcuts
  File ".../cubeviz/keyboard_shortcuts.py", line 2, in <module>
    from qtpy import QtCore, QtWidgets, QtGui, compat
  File ".../qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

**Comment by pllim** [comment]
In Python 3.6, I still see the same "pip's dependency resolver..." message when mosviz is also installed, but the splash screen shows.

**Comment by ibusko** [comment]
The original JIRA ticket is JDAT-1296.

**Comment by eteq** [comment]
In some out-of-band discussion, I think we settled on the following solution:

* Set the  maximum python version to whatever we know works right now (which I think is 3.6?)
* This has the downside that anyone who pip installs will get a downgrade
* ASAP, we put out a last version that has *none* of the current dependencies (and therefore leads to no downgrades), but just creates the error on import that says "go to jdaviz"

**Comment by pllim** [comment]
I see that there is a very specific pinning here:

https://github.com/spacetelescope/cubeviz/blob/c23e48113afa6ba4971bf483c4c50c9402383f0e/setup.cfg#L16

But I am not sure if it works because `pip install cubeviz` pulls in cubeviz 0.3.1 and specviz 0.7.0 into Python 3.9 env. 🤯

**Comment by pllim** [comment]
Regardless, now I don't quite see the value in releasing anything with max Python version pinning, as the resolver will just grab the last (and older) release without this pin for newer Python versions, which is even worse.

I will proceed to just lift the `python_requires` pin and gut this package out.
