### ISSUE TITLE
Kinematics from Emission Lines (velocity map)

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#60]
SK
Fit one or more Gaussians to an emission line to derive kinematics from multiple gas components.
Derive moments of emission line profiles.

HF
For moments, is this something like CASA functionality?
    * http://casa.nrao.edu/docs/UserMan-old/UserManse41.html
    * http://casa.nrao.edu/docs/CasaRef/image.moments.html

For fitting:
    * http://casa.nrao.edu/docs/UserMan/casa_cookbook007.html#section%3Aanalysis.imfit

If this is going to be a GUI-driven operation, we need to define what parameters will be modifiable in the GUI

Imported from Trello https://trello.com/c/XNMsGZsj

**Comment by brechmos-stsci** [comment]
@hcferguson if we interpret this as 1D then the functionality in specviz and other work partially encapsulates this.  Specviz does not have moments yet -- that will have to be worked on.

**Comment by nmearl** [comment]
Including moments in the specviz analytics module should not be difficult.
