### ISSUE TITLE
Make it faster to read gzipped fits files

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#68]
Imported from Trello https://trello.com/c/mbJCXD9L

**Comment by brechmos-stsci** [comment]
Glue issue  ( @astrofrog )

**Comment by astrofrog** [comment]
This is probably not a glue issue but an Astropy issue? (or does glue take a lot longer than astropy?)

**Comment by drdavella** [comment]
I suspect there's actually nothing to be gained here. Astropy is using standard compression packages, so I'm not sure how we'll be able to do much better than that. If anything, there is probably a selection bias involved here where zipped files tend to be much larger than non-zipped ones (hence why they are compressed to begin with), and so loading them necessarily takes longer.

**Comment by astrofrog** [comment]
The other main difference is that non-gzipped files are memory-mapped in glue, making them much faster to read in.

**Comment by brechmos-stsci** [comment]
Ok. Closing this. We can re-open if there is a specific problem that can be reported.
