### ISSUE TITLE
Smart labels for axes

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#69]
Smart labels for axes (using "wavelength" or "frequency" as appropriate, for example)

Imported from Trello https://trello.com/c/b37rQiY0

**Comment by brechmos-stsci** [comment]
Need to spec this out in more detail and more use cases ( @hcferguson @kassin )

**Comment by nmearl** [comment]
Axes should already identify and show given unit information, both in Glue and SpecViz.

**Comment by brechmos-stsci** [comment]
This is probably somewhat related to #99 as well.

**Comment by brechmos-stsci** [comment]
Old ticket
