### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#71]
- [x] Installation instructions (See https://github.com/spacetelescope/cube-tools/wiki/demos for install video)
- [x] updated readme file on github with pointers to tutorials and videos (https://github.com/spacetelescope/cube-tools)
- [x] tutorial for "getting started" -- basically walking through first steps to load and view a cube after installing glue (see https://github.com/spacetelescope/cube-tools/wiki/demos for demo videos)
- [ ] screencast of basic workflow....possible items to cover in a separate card
- [ ] smoothing tutorial python notebook
- [ ] continuum-subtraction tutorial ipython notebook
- [ ] velocity map tutorial python notebook

Imported from Trello https://trello.com/c/LRabPwpm

**Comment by brechmos-stsci** [comment]
This still needs to be done, but will have to do the high priority features first.

**Comment by hcferguson** [comment]
Closing this issue. The screencast is covered in #87. The other open items are things we should have, but are independent of cubeviz (they are notebooks).
