### ISSUE TITLE
Smoothing - in Glue

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#74]
SK
Ivo has een investigating different ways of smoothing:
https://github.com/spacetelescope/cube-tools/blob/master/smoothing/smoothing_recipe.ipynb
The idea is to implement the best method in Glue.

Python notebook: explore what tools we can use
Glue: implement best one

From Ivo's notebook, the best way is to use "convolve" in a loop. Is there a way to do this without using a loop?
```
inter = np.zeros(shape=datacube.shape) # result of first pass (2-D smoothing) goes here
result = np.zeros(shape=datacube.shape) # final result goes here

k1 = Gaussian1DKernel(1.5) # spectral (1-D) kernel
k2 = AiryDisk2DKernel(2.) # spatial (2-D) kernel

start_time = time.time()

# spatial smoothing
for i in range(datacube.shape[0]):
inter[i,:,:] = convolve(datacube[i,:,:], k2)
# spectral smoothing
for i in range(datacube.shape[1]):
for j in range(datacube.shape[2]):
result[:,i,j] = convolve(inter[:,i,j], k1)
```

IB
I added some internal timing information for the loops in the 2D/1D smoothing algorithm in

https://github.com/spacetelescope/cube-tools/blob/master/smoothing/smoothing_recipe.ipynb

Note that the loop statement themselves have a negligible execution time. The calls to the convolve function totally dominate the execution time. Looping is not the big deal it used to be in the early days of Python (as was discussed at SciPy).

I wouldn't entirely discard the use of scipy's gaussian_filter as an option in a GUI tool. There might be use cases where gaussian smoothing along the three cube axis is appropriate. GUI tools are better appreciated when the user gets a very quick response from a user-initiated action. When the expected response time is long, the GUI should provide some visual feedback when engaged in such long computations as with the mixed 2D/1D smoothing. A progress bar or something of the sort.

SK
UI from Susan & David

A spatial smoothing option should be given in the image control panel which is currently labeled "Plot options - image widget." The smoothing option should be labeled "Gaussian smoothing" and look something like this:

Gaussian Smoothing
* x box to enter Gaussian sigma
* y box to enter Gaussuan sigma
* button to revert to original

A spectral smoothing option should be given in the in spectral control panel
which is currently labeled "Plot Options." It should look something like
this:
* Gaussian Smoothing
* lambda box to enter Gaussian sigma
* button to revert to original

Imported from Trello https://trello.com/c/91FqiaBx

**Comment by brechmos-stsci** [comment]
Currently a PR is here https://github.com/spacetelescope/cubeviz/pull/55  @robelgeda please close this when the PR is done and tested.

**Comment by robelgeda** [comment]
Will integrate smoothing after CubeViz GUI gets a mechanism for calling the smoothing GUI. The best way to do this is being planed now.

**Comment by robelgeda** [comment]
Smoothing has been integrated in PR #108

**Comment by robelgeda** [comment]
Please see #128 for smoothing capabilities.
