### ISSUE TITLE
2 wavelength axes in specview

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#76]
2 wavelength axes in specview: rest-frame and observed with an editable box to enter redshift to change the rest-frame axis

Imported from Trello https://trello.com/c/bTFs8dLu

**Comment by brechmos-stsci** [comment]
@hcferguson and @kassin need to test it and sign off.  This is not really a cubeviz thing but should be a specviz thing.

**Comment by nmearl** [comment]
This is a SpecViz thing already: the ability to change the top axis by giving a redshift amount.
