### ISSUE TITLE
Glue should do something intelligent with error

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#79]
Glue should do something intelligent with error (or inverse-variance and mask)

* don't use masked pixels in autoscaling
* light grey for uncertainties in 1-d spectral plots
* demo the ability to select extensions

PDF: https://trello-attachments.s3.amazonaws.com/555b6595957ea0e3077db1ce/55647d68a34f7e774d72721c/d03f2dcfc455cbdefe33bb433d01080b/Interpreting_error_extensions.pdf

(Lots of information on the trello board)

Imported from Trello https://trello.com/c/AmddoGr9

**Comment by brechmos-stsci** [comment]
@kassin this is related to masks in cubeviz data.

**Comment by nmearl** [comment]
I re-read the trello card and I'm not quite sure what is meant by "demo the ability to select extensions" -- was this discussed at all?

**Comment by brechmos-stsci** [comment]
This is done.
