### ISSUE TITLE
Use cube data object consistently in Glue

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#81]
SK
need a discussion on how to work with fits/wcs- Nick should talk with Nadia and Jonathan

along these lines, make sure the cube loaders are combines.
depends on how we will make the final data object that interfaces with specview.
Glue can be "tricked" to think of our cube object as an array.

Imported from Trello https://trello.com/c/Dg5UikTV

**Comment by brechmos-stsci** [comment]
@nmearl we think this is done?  If so, please close.

**Comment by nmearl** [comment]
This has almost entirely been addressed, closing.
