### ISSUE TITLE
Mouse over spectral display and moving regions where the spectrum is constantly updated

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#82]
SK
Jonathan is looking into using Ginga in addition to the Glue viewer.
This is something to bring up with Tom next week.
Harry: elevate the priority of the image tool in Glue

Imported from Trello https://trello.com/c/8zh01EZg

**Comment by brechmos-stsci** [comment]
@nmearl is this done?

**Comment by brechmos-stsci** [comment]
Move mouse around and have spectrum update automatically.  (maybe average over a region around the mouse, maybe lock spectrum too).

**Comment by nmearl** [comment]
Region moving is something that needs to be implemented at the Glue-level. Currently, you can move a sub set region, but while it's being moved, it does not report its current location. @astrofrog

**Comment by astrofrog** [comment]
I'm looking into how we can enable this
