### ISSUE TITLE
2D Moment Maps

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#90]
@hcferguson  ~~cubetools~~ spectral_cube can compute them. Is the set of things complete enough for us?  (1st 2nd etc).  If all in spectral_cube then cubeviz needs an interface. If not, then we should put more functionality into ~~cubetools~~ spectral_cube. For example, how does it deal with masks and errors.

**Comment by brechmos-stsci** [comment]
@nmearl @kassin I am confused, which cubetools? I see https://github.com/astrofrog/cube-tools but it is just a fork of cubeviz and is empty as far as I can tell.

**Comment by brechmos-stsci** [comment]
So, https://github.com/radio-astro-tools/spectral-cube has a moment function:
```
    def moment(self, order=0, axis=0, how='auto'):
        """
        Compute moments along the spectral axis.
        Moments are defined as follows:
        Moment 0:
        .. math:: M_0 \\int I dl
        Moment 1:
        .. math:: M_1 = \\frac{\\int I l dl}{M_0}
        Moment N:
        .. math:: M_N = \\frac{\\int I (l - M_1)^N dl}{M_0}
        .. warning:: Note that these follow the mathematical definitions of
                     moments, and therefore the second moment will return a
                     variance map. To get linewidth maps, you can instead use
                     the :meth:`~SpectralCube.linewidth_fwhm` or
                     :meth:`~SpectralCube.linewidth_sigma` methods.
        Parameters
        ----------
        order : int
           The order of the moment to take. Default=0
        axis : int
           The axis along which to compute the moment. Default=0
        how : cube | slice | ray | auto
           How to compute the moment. All strategies give the same
           result, but certain strategies are more efficient depending
           on data size and layout. Cube/slice/ray iterate over
           decreasing subsets of the data, to conserve memory.
           Default='auto'
        Returns
        -------
           map [, wcs]
           The moment map (numpy array) and, if wcs=True, the WCS object
           describing the map
        Notes
        -----
        Generally, how='cube' is fastest for small cubes that easily
        fit into memory. how='slice' is best for most larger datasets.
        how='ray' is probably only a good idea for very large cubes
        whose data are contiguous over the axis of the moment map.
        For the first moment, the result for axis=1, 2 is the angular
        offset *relative to the cube face*. For axis=0, it is the
        *absolute* velocity/frequency of the first moment.
        """
```
I ran a dataset from a previous set of work through the moment function:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/18348847/32109048-91711038-bb01-11e7-8d6f-770077daac96.png">

So, it seems the spectral_cube repo should be enough.  So, it seems cubeviz should just need an interface.  @kassin and/or @nmearl sound about right?

**Comment by nmearl** [comment]
Yes, this was decided awhile back: to use spectral-cube's pre-built moment machinery, as well as its generic function passing mechanism for arbitrary analytical functionality across cube data.

**Comment by hcferguson** [comment]
Agreed, the math should be in spectra-cube. Looks like it may not deal with masks as written. That would allow the user to mask out pixels to ignore when calculating the moments. 

Then there's a decision to be made about how to generate the masks, either from a DQ file, or by applying a threshold to the data or a threshold to an error array. In a non-GUI workflow it's fine to just show the user how to make such masks. But we might have to think about the most common use case for this and expose it in the GUI. Thinking aloud -- possibly hide this functionality in an "advanced" submenu?
- if there is a mask present, provide a checkbox to ignore masked pixels
- Treat DQ files as masks (i.e require 0=good, and ignore anything nonzero if option is checked)
- If error array is present, provide a slider & text box to allow people to reject pixels with large uncertainties
- Provide a slider & text box to allow people to reject pixels below a certain flux threshold (same for all wavelengths)

**Comment by brechmos-stsci** [comment]
@nmearl @hcferguson @kassin @astrofrog  
I assume for this work there are two parts:

1. Interface: GUI interaction so the user can select the moment in order to process the data.
2. Backend: Tying in spectral-cube moments into cubeviz.

I would like to start with the interface GUI part, but I am not sure how "we" are going to define the UI.  Will it just be a drop-down or off of the menu bar?
![image](https://user-images.githubusercontent.com/18348847/32340815-08893d60-bfd2-11e7-9dc7-2e7e683c9820.png)

Who should I talk with to define how this is going to look? It seems like a larger question as several image processing things will be included over the next little while.

**Comment by kassin** [comment]
Law: for velocity maps, the orientation of the red-blue color map should be flipped such that the redshifted wavelengths are red and the blueshifted wavelengths are blue.

**Comment by kassin** [comment]
Or, be able to invert any color map...

**Comment by bethanjames** [comment]
@kassin @brechmos-stsci @nmearl When we say 'moment maps' are we referring to velocity, fwhm maps etc? If so, how are we deriving these maps without actually fitting the emission/absorption lines?

**Comment by hcferguson** [comment]
@bethanjames One usually takes the moments over a limited wavelength range where you are dominated by a single emission line. Fitting is generally better but much slower. Ultimately the tool should have both options.

**Comment by bethanjames** [comment]
@hcferguson thanks for the clarification! I agree, fitting is slower, although I'd be worried about the level of accuracy achieved without it. Perhaps within the tool we could label the non-fitting option as 'quick look moment maps'? That way the user knows that these maps may not be up to the science grade that they ultimately want.

**Comment by brechmos-stsci** [comment]
(Small aside, @javerbukh talked to me and probably won't have time to work on this so I am going to take it on as the primary person).

**Comment by brechmos-stsci** [comment]
@astrofrog Ah, so something interesting just came up that I had not thought through yet. The moment-map calculation collapses the cube to be a single image (e.g, 74x74) from the original dataset of 74x74x4563 (in this case).  Then when I tried to add the moment-map image into the data it complains they are of different sizes.

I believe this is going to happen on more functionality (e.g., spatial or spectral cropping etc).  I am not strong on the underlying data collection mechanism in Glue so not sure the best way to proceed.  Here are my thoughts:

1. If we could create the functionality to have different cube sizes (degernate or not) in the data object within the Data Collection, then that would probably be best.

2. If we need to create a new Data object within the Data Collection that represents the same underlying data generally but has been processed then we will need to change some functionality in Cubeviz.  (The dropdowns will have to represent not just component but data and component. The sliders will have to be smarter, if things are linked and of different sizes, or we don't allow linking if the cube sizes are not the same (at least in the spectral dimension).)

@astrofrog, Your thoughts on how to proceed with this?

@drdavella feel free to add other comments if I missed something important.

cc @kassin @hcferguson

**Comment by brechmos-stsci** [comment]
Update on this ticket, generally. I have the moment map implemented (to use spectral-cube). We will just need to figure out how to add the dataset back into Glue in order to visualize it (hence the question above).

**Comment by nmearl** [comment]
In my cursory thinking about this in previous sprints, I had always assumed that most results that do not end with the production of a cube-like object, would not be visible in the cubeviz viewer. That is, they would open in a new tab, as a new Glue data object, using traditional viewers. Seems like would be best to separate the functionality between operations and interaction that can be done over cubes explicitly, and everything else.

**Comment by brechmos-stsci** [comment]
@nmearl We looked at that a bit and if we do it that way then I don't think we could view the flux map and moment map side by side if the moment map is loaded into a new tab.  (right @astrofrog ?)

If that is the case then I think there is a larger usability question.

@hcferguson @kassin @bethanjames @drlaw1558 @nmearl   How important is it to be able to see the flux image and calculated moment map image side by side?  

If this must be possible then @drdavella and I can re-work things a bit.  (the question of being able to view calculated images side-by-side with the flux image will apply to lots of calculated images that don't result in same size cubes)

**Comment by hcferguson** [comment]
@nmearl From my perspective it is more important to be able to blink between them or overlay one on the other, rather than see them side by side. But I've found that's often a matter of personal taste.

**Comment by brechmos-stsci** [comment]
@hcferguson The other idea that @drdavella and I were talking about is to have the ability to plot an overlay maybe down at the level of matplotlib.  Then we would not have to be concerned about "linking" of different size cubes. The overlay would be strictly that, just an overlay.  For this milestone we could bite off the "same size" overlay and leave different size overlays for a different set of work.  (make sense?)

**Comment by hcferguson** [comment]
@brechmos-stsci That sounds like the most practical approach to me. It's important to be able to remove it easily. Also very useful to be able to toggle it on and off.
