### ISSUE TITLE
Spectral ROIs not showing up in plot layers

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#93]
Spectral ROIs not showing up in plot layers as they do in specviz:

![image](https://user-images.githubusercontent.com/18348847/32625305-e49f9344-c559-11e7-9eb8-d39e7533402d.png)

cc @nmearl @kassin

**Comment by nmearl** [comment]
I'm not sure I understand what you mean, can you explain a little more?

**Comment by brechmos-stsci** [comment]
@kassin was showing us that in specviz when you create an ROI the label shows up in the Plot Layers - SpecViz Viewer as another entry. Then you can right click on it and change the name.  Then you can use the purple icon in the bottom left to do basic arithmetic on it and create new entries (to plot). 

When we created new ROI in the spectral viewer in cubeviz they did not show up in the Plot Layers - Specviz Viewer area.

**Comment by nmearl** [comment]
That is not how ROIs work. To create a new layer, you must "Slice" the area you've selected with an ROI; the ROI itself does not automatically create a new layer object.

![nov-10-2017 10-23-04](https://user-images.githubusercontent.com/4141126/32665112-413440bc-c601-11e7-97f5-c8dd51a1f3f3.gif)

**Comment by brechmos-stsci** [comment]
@nmearl Ok, got it, I am able to create a layer from an ROI selection as the graphic above shows.  What I don't believe we have, yet, is the ability to display the resulting layer as an image in our image views in cubeviz. 

When I create a slice, what does the layer represent?  (Is this the spectral cropping?  Or is this projecting the spectral information per, pixel/spaxel, into an image?)

**Comment by nmearl** [comment]
This slice exists in SpecViz as a truncated view of the original spectrum. To have this propagate back to the cube object would mean that we'd have to create a new cube object that has the same truncated spectral range.

This could be a new data object, in which case, the user would have to select it from the left panel in Glue in order for all viewers to now display a brand new cube object. But this raises the issue that now you're accessing to distinct data object from the same view (i.e. in SpecViz, a spectrum that represents the original "full" cube, and a truncated spectrum that is attached to a newly created cube).

Is this what you're thinking?
